# $OpenBSD: Makefile,v 1.5 2011/07/30 19:43:05 stephan Exp $

COMMENT =	CCK content field to add a URL to content types

DISTNAME = 	link-6.x-2.9
PKGNAME =	drupal6-link-2.9
REVISION =	1

RUN_DEPENDS =	www/drupal6/cck

.include <bsd.port.mk>
