# $OpenBSD: Makefile,v 1.4 2015/09/20 15:09:36 kili Exp $

COMMENT =		obtain getifaddrs(3) information from Haskell

DISTNAME =		network-info-0.2.0.5
REVISION =		1
CATEGORIES =		net

HOMEPAGE =		https://github.com/jystic/network-info

MAINTAINER =		David Schaefer <dawedawe@gmx.de>

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

MODGHC_PACKAGE_KEY =	DC4wOVa57ku5PvsB1dnQbi

.include <bsd.port.mk>
