# $OpenBSD: Makefile,v 1.90 2005/01/23 23:57:16 jakob Exp $

VERSION=	2.2-20050119
DISTNAME=	postfix-${VERSION}
PKGNAME=	postfix-${VERSION:S/-/./}

MAINTAINER=	Jakob Schlyter <jakob@openbsd.org>

MASTER_SITES=	${MASTER_SITE_POSTFIX:=experimental/}

.include <bsd.port.mk>
