COMMENT =		HTTP server toolkit

DISTNAME =		webrick-1.7.0

CATEGORIES =		www

HOMEPAGE =		https://github.com/ruby/webrick

# Ruby, MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/ruby

CONFIGURE_STYLE =	ruby gem

.include <bsd.port.mk>
