# $OpenBSD: Makefile,v 1.9 2015/02/16 22:57:10 naddy Exp $

COMMENT=		dhcp daemon ping program

VERSION=		1.2
DISTNAME=		dhcping-${VERSION}
CATEGORIES=		net

HOMEPAGE=		http://www.mavetju.org/unix/general.php

MASTER_SITES=		http://www.mavetju.org/download/

# GPL
PERMIT_PACKAGE_CDROM=	Yes
WANTLIB=		c

CONFIGURE_STYLE=	gnu

.include <bsd.port.mk>
