# $OpenBSD: Makefile,v 1.11 2015/11/05 19:08:57 jca Exp $

COMMENT=        cryptographic signatures for objects

MODULES=	cpan
DISTNAME=	Object-Signature-1.05
REVISION=	3
CATEGORIES=     devel

# perl
PERMIT_PACKAGE_CDROM=   Yes

MAKE_ENV=	AUTOMATED_TESTING=Yes TEST_POD=Yes

.include <bsd.port.mk>
