# $OpenBSD: Makefile,v 1.1.1.1 2008/07/09 11:20:43 landry Exp $

COMMENT=		tiling window management for the console

DISTNAME=		dvtm-0.4.1
CATEGORIES=		misc

HOMEPAGE=		http://www.brain-dump.org/projects/dvtm/
MAINTAINER=		Emilien Gaspar <gapz@dud-t.org>

# MIT/X
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=	Yes

WANTLIB= 		c ncurses util

MASTER_SITES=		${HOMEPAGE}

NO_REGRESS=     	Yes

.include <bsd.port.mk>
