# $OpenBSD: Makefile,v 1.14 2003/01/27 19:42:20 espie Exp $

COMMENT=		"X11 toolkit, edutainment"
CATEGORIES=		x11 x11/kde
VERSION=		3.1
DISTNAME=		kdeedu-${VERSION}

LIB_DEPENDS= kdecore.4,DCOP,kdefx,kdeprint,kdesu,kdeui,khtml,kio,kparts,kutils::x11/kde/libs3
SEPARATE_BUILD=flavored

.include <bsd.port.mk>
