# $OpenBSD: Makefile,v 1.6 2010/10/18 18:36:46 espie Exp $

COMMENT=	command-line LiveJournal client
DISTNAME=	clive-0.4.0
REVISION=	0
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=ljclive/}

HOMEPAGE=	http://community.livejournal.com/ljclive/

MAINTAINER=	Andy Isaacson <adi@hexapodia.org>

# BSD 3-clause
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

WANTLIB=		c

CONFIGURE_STYLE=gnu
USE_GROFF =	Yes

.include <bsd.port.mk>
