# $OpenBSD: Makefile,v 1.3 2019/07/12 20:50:13 sthen Exp $

COMMENT =	ANSII Color formatting for output in terminal

MODPY_EGG_VERSION =	1.1.0
DISTNAME =	termcolor-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}
REVISION =	0

CATEGORIES =	textproc

# MIT
PERMIT_PACKAGE =	Yes

MODULES =	lang/python
MODPY_PI =	Yes

FLAVORS =	python3
FLAVOR ?=

NO_TEST =	Yes

.include <bsd.port.mk>
