# $OpenBSD: Makefile,v 1.5 2020/04/07 21:23:18 sebastia Exp $

COMMENT =		constant autoloading with Ruby semantics

DISTNAME =		zeitwerk-2.3.0
CATEGORIES =		devel
MAINTAINER =		Sebastian Reitenbach <sebastia@openbsd.org>

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/ruby

CONFIGURE_STYLE = 	ruby gem

.include <bsd.port.mk>
