# $OpenBSD: Makefile,v 1.3 2006/12/04 12:07:21 msf Exp $

COMMENT=	"efficient reading/writing of complete files"

MODULES=	cpan
DISTNAME=	File-Slurp-9999.12
CATEGORIES=	devel

MAINTAINER=	Mathieu Sauve-Frankel <msf@openbsd.org>

# Artistic 
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MAKE_ENV=	TEST_POD=Yes

.include <bsd.port.mk>
