# $OpenBSD: Makefile,v 1.6 2014/02/08 19:59:17 espie Exp $

COMMENT =	redirect login screen to https
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	securelogin-6.x-1.x-dev
PKGNAME =	drupal6-securelogin-1
REVISION =	2

.include <bsd.port.mk>
