# $OpenBSD: Makefile,v 1.9 2010/12/03 11:46:47 ajacoutot Exp $

COMMENT=	module to talk to a UPS via NUT (Network UPS Tools) upsd

DISTNAME=	UPS-Nut-0.04
REVISION=	1
CATEGORIES=	sysutils
MODULES=	cpan
USE_GROFF =	Yes

# GPL/Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=	${MASTER_SITE_PERL_CPAN:=../by-authors/id/K/KP/KPETERS/}

.include <bsd.port.mk>
