#!/bin/sh
#
# $OpenBSD: mod_mp3-enable,v 1.1.1.1 2003/05/20 01:57:18 naddy Exp $

MODULE=!!PREFIX!!/lib/mod_mp3.so

if [ `id -u` -ne 0 ]; then
	echo "You must be root to run this script."
	exit
fi

if [ ! -f ${MODULE} ]; then
	echo "Cannot find mod_mp3 module (${MODULE})"
	exit 1
else
	echo "Enabling MP3 module..."
	/usr/sbin/apxs -i -a -n mp3 ${MODULE}
fi
