# $OpenBSD: Makefile,v 1.4 2005/03/02 14:28:28 mbalmer Exp $

COMMENT=	"class for generating HTML form select elements for PHP"

DISTNAME=	HTML_Select-1.2.1
PKGNAME=	pear-${DISTNAME:S/_/-/}
CATEGORIES=	www pear

MASTER_SITES=	http://pear.php.net/get/
EXTRACT_SUFX=	.tgz

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

MODULES=	www/php5/pear

# PHP License
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=	http://pear.php.net/get/
EXTRACT_SUFX=	.tgz

.include <bsd.port.mk>
