# $OpenBSD: Makefile,v 1.8 2009/11/06 08:32:37 jasper Exp $

COMMENT=	class for generating HTML form select elements for PHP

DISTNAME=	HTML_Select-1.2.1
PKGNAME=	pear-${DISTNAME:S/_/-/}p1
CATEGORIES=	www pear

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

MODULES=	www/pear

# PHP License
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
