COMMENT =		high-performance diff and patch library

MODPY_EGG_VERSION =	20230430
DISTNAME =		diff-match-patch-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}

CATEGORIES =		textproc

MAINTAINER =		Daniel Dickman <daniel@openbsd.org>

# Apache v2
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

FLAVORS =		python3
FLAVOR =		python3

MODPY_PI =		Yes
MODPY_PYBUILD =		flit_core

.include <bsd.port.mk>
