# $OpenBSD: Makefile,v 1.15 2012/08/23 15:05:15 sthen Exp $

COMMENT=	finding memory usage of perl variables
SHARED_ONLY=	Yes

MODULES=	cpan
DISTNAME=	Devel-Size-0.77
REVISION=	0
CATEGORIES=	devel

MAINTAINER=	Jasper Lievisse Adriaanse <jasper@openbsd.org>

# perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

WANTLIB += c

.include <bsd.port.mk>
