# $OpenBSD: Makefile,v 1.6 2010/11/05 07:57:07 sthen Exp $

COMMENT=	to-do list manager

DISTNAME=	tdl-1.5.2
REVISION=	1
CATEGORIES=	productivity

MASTER_SITES=	http://www.rpcurnow.force9.co.uk/tdl/

HOMEPAGE=	http://www.rc0.org.uk/tdl/

MAINTAINER=	Morten Liebach <m@mongers.org>

WANTLIB=	c readline termcap

# GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE= simple

USE_GROFF=	Yes
NO_REGRESS=	Yes

.include <bsd.port.mk>
