MODGO_MODULES =	\
	github.com/a8m/tree		 v0.0.0-20210115125333-10a5fd5b637d \
	github.com/creack/pty		 v1.1.9 \
	github.com/dougm/pretty		 v0.0.0-20171025230240-2ee9d7453c02 \
	github.com/google/uuid		 v1.3.0 \
	github.com/kr/pretty		 v0.3.0 \
	github.com/kr/pty		 v1.1.1 \
	github.com/kr/text		 v0.2.0 \
	github.com/rasky/go-xdr		 v0.0.0-20170217172119-4930550ba2e2 \
	github.com/rogpeppe/go-internal	 v1.6.1 \
	github.com/vmware/vmw-guestinfo	 v0.0.0-20170707015358-25eff159a728 \
	gopkg.in/check.v1		 v1.0.0-20180628173108-788fd7840127 \
	gopkg.in/errgo.v2		 v2.1.0

MODGO_MODFILES =	\
	github.com/kr/pretty	 v0.1.0 \
	github.com/kr/text	 v0.1.0
