#!/bin/sh
# $OpenBSD: DEINSTALL,v 1.2 2003/06/22 17:24:42 sturm Exp $
#
# privoxy de-installation

set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
CONFIG_DIR=${SYSCONFDIR}/privoxy
LOG_DIR=/var/log/privoxy

echo
echo "+---------------"
echo "| To completely deinstall the $1 package you need to perform"
echo "| these steps as root:"
echo "|"
echo "|           rm -rf $CONFIG_DIR"
echo "|           rm -rf $LOG_DIR"
echo "|           rmuser _privoxy"
echo "|"
echo "| Do not do this if you plan on re-installing $1"
echo "| at some future time."
echo "+---------------"
echo

exit 0
