# $OpenBSD: Makefile,v 1.1.1.1 2019/05/09 11:48:51 semarie Exp $

MODPY_EGG_VERSION =	5.2.0
TRYTON_MODULE =		account_dunning_email

TRYTON_DEPENDS +=	account_dunning \
			account_dunning_letter \
			party

.include <bsd.port.mk>
