# $OpenBSD: Makefile,v 1.8 2016/03/20 19:56:16 naddy Exp $

COMMENT=	xpath matching for object trees

MODULES=	cpan
PKG_ARCH=	*
DISTNAME=	Class-XPath-1.4
REVISION=	0
CATEGORIES=	devel textproc

MAINTAINER=	Sam Smith <s@msmith.net>

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
