COMMENT =		perl module to guess file type from contents

DISTNAME =		File-MMagic-1.30
REVISION =		0

CATEGORIES =		misc

MAINTAINER =		Alexander Bluhm <bluhm@openbsd.org>

# misc, Apache
PERMIT_PACKAGE =	Yes

MODULES =		cpan
PKG_ARCH =		*

.include <bsd.port.mk>
