# $OpenBSD: Makefile,v 1.4 2013/03/11 10:50:21 espie Exp $

COMMENT=	syntactic sugar for lambdas in Perl

DISTNAME=	Sub-Lambda-0.02
REVISION=	0
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes

MODULES=	cpan

USE_GROFF=	Yes

RUN_DEPENDS=	devel/p5-Parse-RecDescent

.include <bsd.port.mk>
