# $OpenBSD: Makefile,v 1.9 2014/04/29 09:39:34 ajacoutot Exp $

TRYTOND_MODULE =	product_price_list
REVISION =		0

RUN_DEPENDS =		productivity/tryton/company \
			productivity/tryton/party \
			productivity/tryton/product

.include <bsd.port.mk>
