# $OpenBSD: Makefile,v 1.5 2012/01/08 12:03:09 sebastia Exp $

COMMENT =	tetris like puzzle game

DISTNAME =	LapisPuzzle-1.2
CATEGORIES =	games

HOMEPAGE =	http://gap.nongnu.org/lapispuzzle/
MASTER_SITES =	${MASTER_SITE_SAVANNAH:=gap/}

MODULES =	x11/gnustep
WANTLIB += 	c m pthread

.include <bsd.port.mk>
