# $OpenBSD: Makefile,v 1.7 2016/03/19 21:18:38 naddy Exp $

COMMENT=	reusable split of pecl_http's property proxy API#'

DISTNAME=	propro-1.0.0
REVISION=	3

# PHP
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB=	c

MODULES=	lang/php/pecl
CONFIGURE_STYLE= gnu

.include <bsd.port.mk>
