# $OpenBSD: Makefile,v 1.5 2010/12/03 11:46:53 ajacoutot Exp $
COMMENT=	HTML ajax autocompleter for Rose

MODULES=	cpan
DISTNAME=	Rose-HTMLx-Form-Field-Autocomplete-0.02
REVISION=	0
CATEGORIES=	www devel databases
USE_GROFF =	Yes

RUN_DEPENDS=	www/p5-Rose-HTML-Objects


# Perl
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes

.include <bsd.port.mk>
