# $OpenBSD: Makefile,v 1.10 2018/01/20 11:35:50 ajacoutot Exp $

PROVIDER=		alicloud
GH_TAGNAME=		V1.6.1

PORTROACH=		skipv:${GH_TAGNAME}
DISTNAME=		${GH_PROJECT}-${GH_TAGNAME:L:C/^v//}
WRKDIST=		${WRKDIR}/${DISTNAME}

.include <bsd.port.mk>
