# $OpenBSD: Makefile,v 1.16 2010/02/01 17:00:12 espie Exp $

     SUBDIR =
     SUBDIR += AsteriskTFOT
     SUBDIR += JLS
     SUBDIR += autobook
     SUBDIR += clisp-hyperspec
     SUBDIR += cvs-guide
     SUBDIR += diveintopython
     SUBDIR += docbook-guide
     SUBDIR += grokking-the-gimp
     SUBDIR += haskell-report
     SUBDIR += mason-book
     SUBDIR += svnbook
     SUBDIR += thinking-forth
     SUBDIR += vol3ol
     SUBDIR += vol6a
     SUBDIR += wndw
     SUBDIR += zopebook

.include <bsd.port.subdir.mk>
