MODGO_MODULES =	\
	github.com/cpuguy83/go-md2man/v2	 v2.0.2 \
	github.com/fatih/color			 v1.15.0 \
	github.com/google/uuid			 v1.3.0 \
	github.com/inconshreveable/mousetrap	 v1.1.0 \
	github.com/mattn/go-colorable		 v0.1.13 \
	github.com/mattn/go-isatty		 v0.0.19 \
	github.com/pin/tftp/v3			 v3.0.0 \
	github.com/russross/blackfriday/v2	 v2.1.0 \
	github.com/spf13/cobra			 v1.7.0 \
	github.com/spf13/pflag			 v1.0.5 \
	golang.org/x/crypto			 v0.12.0 \
	golang.org/x/net			 v0.11.0 \
	golang.org/x/sys			 v0.11.0 \
	golang.org/x/term			 v0.11.0 \
	golang.org/x/text			 v0.12.0 \
	gopkg.in/check.v1			 v0.0.0-20161208181325-20d25e280405 \
	gopkg.in/yaml.v3			 v3.0.1

MODGO_MODFILES =	\
	github.com/mattn/go-isatty	 v0.0.16 \
	github.com/mattn/go-isatty	 v0.0.17 \
	golang.org/x/crypto		 v0.0.0-20190308221718-c2843e01d9a2 \
	golang.org/x/crypto		 v0.10.0 \
	golang.org/x/net		 v0.0.0-20200202094626-16171245cfb2 \
	golang.org/x/net		 v0.10.0 \
	golang.org/x/sys		 v0.0.0-20190215142949-d0b11bdaac8a \
	golang.org/x/sys		 v0.0.0-20220811171246-fbc7d0a398ab \
	golang.org/x/sys		 v0.6.0 \
	golang.org/x/sys		 v0.9.0 \
	golang.org/x/term		 v0.9.0 \
	golang.org/x/text		 v0.10.0 \
	golang.org/x/text		 v0.3.0
