# $OpenBSD: Makefile,v 1.4 2012/05/02 06:57:54 ajacoutot Exp $

MODPY_EGG_VERSION =	2.4.0
TRYTOND_MODULE =	project_revenue

RUN_DEPENDS =		productivity/tryton/project>=2.2.0 \
			productivity/tryton/product>=2.2.0 \
			productivity/tryton/timesheet>=2.2.0

.include <bsd.port.mk>
