# $OpenBSD: Makefile,v 1.17 2015/09/29 10:52:32 sthen Exp $

TRYTOND_MODULE =	project_revenue
REVISION =		0

RUN_DEPENDS =		productivity/tryton/project \
			productivity/tryton/product \
			productivity/tryton/timesheet_cost \
			productivity/tryton/company

.include <bsd.port.mk>
