# $OpenBSD: Makefile,v 1.11 2016/03/20 19:56:39 naddy Exp $

COMMENT =	case preserving but case insensitive hash table

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	Tie-CPHash-2.000
CATEGORIES =	devel

# perl
PERMIT_PACKAGE_CDROM =	Yes

CONFIGURE_STYLE =	modinst

.include <bsd.port.mk>
