# $OpenBSD: Makefile,v 1.4 2010/12/03 11:46:48 ajacoutot Exp $

COMMENT =	Template Toolkit renderer for Mojo

MODULES =	cpan
DISTNAME =	MojoX-Renderer-TT-0.20
REVISION =	0
CATEGORIES =	textproc
USE_GROFF =	Yes

# Perl
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

CPAN_AUTHOR =		ABH

RUN_DEPENDS =		textproc/p5-Template \
			www/p5-Mojo

.include <bsd.port.mk>
