MODGO_MODULES =	\
	github.com/anacrolix/envpprof	 v1.0.0 \
	github.com/anacrolix/ffprobe	 v1.1.0 \
	github.com/anacrolix/missinggo	 v1.1.0 \
	github.com/bradfitz/iter	 v0.0.0-20140124041915-454541ec3da2 \
	github.com/davecgh/go-spew	 v1.1.0 \
	github.com/nfnt/resize		 v0.0.0-20180221191011-83c6a9932646 \
	github.com/pmezard/go-difflib	 v1.0.0 \
	github.com/stretchr/testify	 v1.3.0 \
	golang.org/x/crypto		 v0.49.0 \
	golang.org/x/net		 v0.52.0 \
	golang.org/x/sys		 v0.42.0 \
	golang.org/x/term		 v0.41.0 \
	golang.org/x/text		 v0.35.0
