$OpenBSD: patch-style_Makefile.sub,v 1.2 2002/07/28 06:59:49 brad Exp $
--- style/Makefile.sub.orig	Wed Sep  1 03:25:59 1999
+++ style/Makefile.sub	Sun Jul 28 02:59:43 2002
@@ -33,6 +33,7 @@ GENSRCS=style_inst.cxx FlowObj_inst.cxx 
 
 FlowObj.o: FlowObj_inst.cxx
 primitive.o: primitive_inst.cxx
+	$(CXX) $(ALL_CXXFLAGS) -O0 -c primitive.cxx
 DssslApp.o: DssslAppMessages.h
 FlowObj.lo: FlowObj_inst.cxx
 primitive.lo: primitive_inst.cxx
