# $OpenBSD: Makefile,v 1.12 2011/05/24 16:26:00 jasper Exp $

     SUBDIR =
     SUBDIR += backgrounds
     SUBDIR += desktop
     SUBDIR += devhelp
     SUBDIR += eog
     SUBDIR += eog-plugins
     SUBDIR += gdl
     SUBDIR += gedit
#     SUBDIR += gedit-plugins
     SUBDIR += icon-theme
     SUBDIR += icon-theme-extras
     SUBDIR += icon-theme-symbolic
     SUBDIR += keyring
     SUBDIR += libgnome-keyring
     SUBDIR += libgnomekbd
     SUBDIR += libgweather
     SUBDIR += menus
     SUBDIR += metacity
     SUBDIR += nautilus
     SUBDIR += nettool
     SUBDIR += panel
     SUBDIR += session
     SUBDIR += settings-daemon
     SUBDIR += terminal
     SUBDIR += totem
     SUBDIR += user-docs
     SUBDIR += utils
     SUBDIR += video-arcade
     SUBDIR += yelp
     SUBDIR += zenity

.include <bsd.port.subdir.mk>
