# $OpenBSD: Makefile,v 1.4 2013/03/11 11:41:25 espie Exp $

COMMENT =		platform independent entropy source

DISTNAME =		entropy-0.2.1
REVISION =		1
CATEGORIES =		security

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ghc

MODGHC_BUILD =		cabal hackage haddock register

.include <bsd.port.mk>
