# $OpenBSD: Makefile,v 1.29 2013/10/11 21:21:05 naddy Exp $

COMMENT=	X11 fonts (.bdf files) editor

DISTNAME=	xfed
PKGNAME=	xfed-1.0
REVISION=	1
CATEGORIES=	x11 fonts

# original site no longer available.
MASTER_SITES=	http://spacehopper.org/mirrors/

# License: BSD
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB=		X11 Xau Xdmcp Xext c

CONFIGURE_STYLE=	imake

NO_TEST=	Yes

.include <bsd.port.mk>
