# $OpenBSD: Makefile,v 1.1.1.1 2019/05/04 01:40:22 afresh1 Exp $

COMMENT =	Mojolicious Thumbnail Plugin

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	Mojolicious-Plugin-Thumbnail-0.01

CATEGORIES =	www

MAINTAINER =	Olivier Cherrier <oc@symacx.com>

# Perl
PERMIT_PACKAGE_CDROM =		Yes

RUN_DEPENDS =	www/p5-Mojo \
		graphics/p5-Imager

.include <bsd.port.mk>
