COMMENT=	provides a generic logging layer

VERSION=	0.0.10
DISTNAME=	vanessa_logger-${VERSION}
REVISION=	1

SHARED_LIBS=	vanessa_logger			1.0	# 0.5

SITES=	${SITE_VANESSA:=vanessa_logger/${VERSION}/}

WANTLIB=	c

.include <bsd.port.mk>
