# $OpenBSD: Makefile,v 1.4 2016/09/02 22:42:17 jasper Exp $

COMMENT = 	manage process id files

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	Proc-PID-File-1.28
CATEGORIES =	devel

# GPLv2
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
