# $OpenBSD: Makefile,v 1.16 2015/09/19 21:33:37 ajacoutot Exp $

MODPY_EGG_VERSION =	3.2.4

TRYTOND_MODULE =	account_invoice

RUN_DEPENDS =		productivity/tryton/account_product \
			productivity/tryton/company \
			productivity/tryton/currency \
			productivity/tryton/party \
			productivity/tryton/product

.include <bsd.port.mk>
