# $OpenBSD: Makefile,v 1.5 2010/10/19 07:54:24 espie Exp $

COMMENT=	match globbing patterns against text

MODULES=	cpan
DISTNAME=	Text-Glob-0.08
CATEGORIES=	textproc
USE_GROFF =	Yes

# same as perl
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes

.include <bsd.port.mk>
