COMMENT =	provides a unified approach to tracing

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	Log-Trace-1.070
REVISION =	2
CATEGORIES =	devel

# GPLv2
PERMIT_PACKAGE =		Yes

MAKE_ENV +=	TEST_POD=1

.include <bsd.port.mk>
