--- esd.c.orig	Mon Oct  2 12:39:17 2000
+++ esd.c	Thu Oct  5 19:39:00 2000
@@ -219,12 +219,12 @@
 	{	
 	  mkdir(ESD_UNIX_SOCKET_DIR,
 		S_IRUSR|S_IWUSR|S_IXUSR|
-		S_IRGRP|S_IWGRP|S_IXGRP|
-		S_IROTH|S_IWOTH|S_IXOTH);
+		S_IRGRP|S_IXGRP|
+		S_IROTH|S_IXOTH);
 	  chmod(ESD_UNIX_SOCKET_DIR,
 		S_IRUSR|S_IWUSR|S_IXUSR|
-		S_IRGRP|S_IWGRP|S_IXGRP|
-		S_IROTH|S_IWOTH|S_IXOTH);
+		S_IRGRP|S_IXGRP|
+		S_IROTH|S_IXOTH);
 	}
       if (access(ESD_UNIX_SOCKET_NAME, R_OK | W_OK) == -1)
 	{
