--- esd.c.orig	Wed Jan  3 08:56:09 2001
+++ esd.c	Wed Jan  3 08:58:00 2001
@@ -210,12 +210,12 @@
 
 #if defined(S_ISVTX)
 #define ESD_UNIX_SOCKET_DIR_MODE (S_IRUSR|S_IWUSR|S_IXUSR|\
-				  S_IRGRP|S_IWGRP|S_IXGRP|\
-				  S_IROTH|S_IWOTH|S_IXOTH|S_ISVTX)
+				  S_IRGRP|S_IXGRP|\
+				  S_IROTH|S_IXOTH|S_ISVTX)
 #else
 #define ESD_UNIX_SOCKET_DIR_MODE (S_IRUSR|S_IWUSR|S_IXUSR|\
-				  S_IRGRP|S_IWGRP|S_IXGRP|\
-				  S_IROTH|S_IWOTH|S_IXOTH)
+				  S_IRGRP|S_IXGRP|\
+				  S_IROTH|S_IXOTH)
 #endif
 
   if (mkdir(ESD_UNIX_SOCKET_DIR, ESD_UNIX_SOCKET_DIR_MODE) == 0) {
