# $OpenBSD: Makefile,v 1.4 2010/10/18 17:48:07 espie Exp $

COMMENT= 	handles various forms of terminal input

MODULES=	cpan

DISTNAME=	Term-Prompt-1.04
CATEGORIES=	devel
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

RUN_DEPENDS=	::devel/p5-Term-ReadKey

.include <bsd.port.mk>
