# $OpenBSD: Makefile,v 1.16 2019/05/20 20:52:34 sthen Exp $

COMMENT=		commandline shell and file manager

DISTNAME=		clex-3.15
CATEGORIES=		misc
REVISION=		1

HOMEPAGE=		http://www.clex.sk/

# GPL
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB=		c curses

MASTER_SITES=		${HOMEPAGE:=download/}

CONFIGURE_STYLE=	gnu

.include <bsd.port.mk>
