MODERL_PLUGINS =	provider_asn1		0.4.1 \
			rebar3_hex		7.0.8 \
			rebar3_fmt		1.18.0 \
			getopt			1.0.1 \
			verl			1.1.1 \
			pc			1.15.0 \
			providers		1.8.1 \
			hex_core		0.10.1

MODERL_MODULES =	base64url		1.0.1 \
			cache_tab		1.0.33 \
			eimp			1.0.26 \
			epam			1.0.14 \
			eredis			1.7.1 \
			esip			1.0.59 \
			ezlib			1.0.15 \
			fast_tls		1.1.25 \
			fast_xml		1.1.57 \
			fast_yaml		1.0.39 \
			idna			6.1.1 \
			jiffy			1.1.2 \
			jose			1.11.10 \
			luerl			1.2.3 \
			mqtree			1.0.19 \
			p1_acme			1.0.28 \
			p1_mysql		1.0.26 \
			p1_oauth2		0.6.14 \
			p1_pgsql		1.1.35 \
			p1_utils		1.0.28 \
			pkix			1.0.10 \
			sqlite3			1.1.15 \
			stringprep		1.0.33 \
			stun			1.2.21 \
			unicode_util_compat	0.7.1 \
			xmpp			1.11.1 \
			yconf			1.0.21
