MODERL_PLUGINS =	\
			provider_asn1		0.2.0 \
			rebar3_hex		7.0.8 \
			verl			1.1.1 \
			pc			1.15.0 \
			hex_core		0.10.1

MODERL_MODULES =	base64url		1.0.1 \
			cache_tab		1.0.31 \
			eimp			1.0.23 \
			epam			1.0.14 \
			eredis			1.2.0 \
			esip			1.0.56 \
			ezlib			1.0.13 \
			fast_tls		1.1.22 \
			fast_xml		1.1.53 \
			fast_yaml		1.0.37 \
			idna			6.0.0 \
			jiffy			1.1.1 \
			jose			1.11.10 \
			lager			3.9.1 \
			luerl			1.2.0 \
			mqtree			1.0.17 \
			p1_acme			1.0.24 \
			p1_mysql		1.0.24 \
			p1_oauth2		0.6.14 \
			p1_pgsql		1.1.26 \
			p1_utils		1.0.26 \
			pkix			1.0.10 \
			sqlite3			1.1.15 \
			stringprep		1.0.30 \
			stun			1.2.15 \
			unicode_util_compat	0.7.0 \
			xmpp			1.9.0 \
			yconf			1.0.16
