# $OpenBSD: Makefile,v 1.5 2013/03/11 10:50:24 espie Exp $

COMMENT =	boolean support for Perl

MODULES =	cpan
DISTNAME =	boolean-0.27
CATEGORIES =	devel

MAINTAINER =	Simon Bertrang <simon@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =		Yes

CPAN_AUTHOR =	INGY

.include <bsd.port.mk>
