# $OpenBSD: Makefile,v 1.10 2014/03/31 15:14:40 robert Exp $

COMMENT=		Maketext from already interpolated strings

MODULES=		cpan
DISTNAME=		Locale-Maketext-Fuzzy-0.11
CATEGORIES=		converters devel
USE_GROFF =		Yes

# GPL
PERMIT_PACKAGE_CDROM=   Yes

.include <bsd.port.mk>
