# OpenBSD makefile for:	leafnode
# Version required:	1.4-7
# Date created:		19 Dec 1997
# Whom:			joey
#
# $OpenBSD: Makefile,v 1.2 1998/07/25 06:16:10 marc Exp $
#

DISTNAME=		leafnode-1.4-7
PKGNAME=		leafnode-1.4.7
CATEGORIES=		news

MAINTAINER=		marc@OpenBSD.ORG

MASTER_SITES=		${MASTER_SITE_SUNSITE}
MASTER_SITE_SUBDIR=	system/news/readers
EXTRACT_SUFX=		.src.elf.tar.gz

NO_PACKAGE=		"won't install correctly"

.include <bsd.port.mk>
