# $OpenBSD: Makefile,v 1.23 2021/10/19 05:59:47 benoit Exp $

COMMENT =	comprehensive set of aliasing operations

MODULES =	cpan
DISTNAME =	Data-Alias-1.25
CATEGORIES =	devel

# Perl
PERMIT_PACKAGE =		Yes

WANTLIB += c perl

.include <bsd.port.mk>
