# $OpenBSD: Makefile,v 1.17 2017/05/12 08:31:27 benoit Exp $

COMMENT = 	Perl library for manipulating frame stack

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	Sub-Uplevel-0.2800
EPOCH =		0
CATEGORIES =	devel

# Perl 5
PERMIT_PACKAGE_CDROM =	Yes

MAKE_ENV =	AUTHOR_TESTING=Yes \
		TEST_POD=Yes

.include <bsd.port.mk>
