COMMENT=	send files to the trash natively

MODPY_DISTV=	1.8.3
DISTNAME=	Send2Trash-${MODPY_DISTV}
PKGNAME=	py-${DISTNAME:L}

CATEGORIES=	devel

HOMEPAGE=	https://github.com/hsoft/send2trash

# BSD
PERMIT_PACKAGE=	Yes

MODULES=	lang/python
MODPY_PYBUILD=	setuptools
MODPY_PI=	Yes
PORTHOME=	${WRKDIR}

.include <bsd.port.mk>
