# $OpenBSD: Makefile,v 1.10 2019/07/12 20:43:29 sthen Exp $

COMMENT =		public domain implementation of the lzip data compressor

DISTNAME =		pdlzip-1.10

HOMEPAGE =		http://lzip.nongnu.org/pdlzip.html
MASTER_SITES =		${MASTER_SITE_SAVANNAH:=lzip/pdlzip/}

# Public domain
PERMIT_PACKAGE =	Yes

WANTLIB =		c

.include <bsd.port.mk>
