# $OpenBSD: Makefile,v 1.17 2020/08/16 19:44:08 afresh1 Exp $

COMMENT=		parse regular expressions

MODULES=		cpan
PKG_ARCH=		*
DISTNAME =		PPIx-Regexp-0.073
CATEGORIES=		textproc

# perl
PERMIT_PACKAGE=	Yes

CPAN_AUTHOR=		WYANT

RUN_DEPENDS=		devel/p5-Task-Weaken \
			textproc/p5-PPI

.include <bsd.port.mk>
