.\" Copyright (c) 2007, Girish Venkatachalam, <girish1729@gmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd June 4, 2008
.Dt MKPLAYLIST 1
.Os
.Sh NAME
.Nm mkplaylist
.Nd create a playlist from directories
.Sh SYNOPSIS
.Nm mkplaylist
.Op Fl chqrv
.Op Fl f Ar playlist_format
.Op Fl o Ar playlist_file
.Sh DESCRIPTION
.Nm
is a small python script that creates m3u, extended m3u or PLS playlists
from ac3, flac, it, mod, mp3, ogg, s3m and wav files.
.Sh OPTIONS
The options are as follows:
.Bl -tag -width Ds
.It Fl c
Use a cache file.
The default is not to use one.
.It Fl h
Show a help message.
.It Fl q
Be really quiet.
.It Fl r
Write relative paths.
The default is to write absolute paths.
.It Fl v
Be verbose.
.It Fl -shuffle
Shuffle the playlist before saving it.
.It Fl o
Output playlist filename.
.El
.Sh EXAMPLES
Create the playlist
.Pa playlist.m3u
from the audio files in the
.Pa /data/music
directory:
.Pp
.Dl mkplaylist --cache -o playlist.m3u /data/music
.Pp
Create a playlist in m3u format with relative paths from
the two directories
.Pa /data/music/Various
and
.Pa /data/music/Soundtracks :
.Bd -literal -offset indent
mkplaylist -r -f m3u --shuffle /data/music/Various \e
                               /data/music/Soundtracks
.Ed
