# $OpenBSD: Makefile,v 1.26 2001/04/19 11:47:32 brad Exp $
# $FreeBSD: Makefile,v 1.3 1999/04/29 15:32:56 rse Exp $

COMMENT=	"GNU Portable Shell Tool"

DISTNAME=	shtool-1.5.3
CATEGORIES=	devel
NEED_VERSION=	1.384
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR= shtool

HOMEPAGE=	http://www.gnu.org/software/shtool/

MAINTAINER=	Brad Smith <brad@openbsd.org>

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE= gnu

.include <bsd.port.mk>
