# $OpenBSD: Makefile,v 1.9 2013/03/11 10:50:20 espie Exp $

COMMENT=	C implementation of priority queues

SHARED_ONLY=    Yes

MODULES=	cpan
DISTNAME=	POE-XS-Queue-Array-0.005
REVISION=	2
CATEGORIES=	devel
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB += c

.include <bsd.port.mk>
