# $OpenBSD: Makefile,v 1.46 2020/02/21 11:28:14 ajacoutot Exp $

COMMENT=		tool for building, changing, and versioning infrastructure

GH_TAGNAME=		v0.12.21
GH_ACCOUNT=		hashicorp
GH_PROJECT=		terraform

.include <bsd.port.mk>
