# $OpenBSD: Makefile,v 1.5 2017/07/15 09:02:20 ajacoutot Exp $

COMMENT=		tool for building, changing, and versioning infrastructure

GH_TAGNAME=		v0.10.0-beta2
GH_ACCOUNT=		hashicorp
GH_PROJECT=		terraform
PKGNAME=		${GH_PROJECT}-0.10.0beta2

.include <bsd.port.mk>
