COMMENT =	analyze Python pickle object serializations

MODPY_EGG_VERSION = 0.1.3
DISTNAME =	fickling-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}
CATEGORIES =	security

MAINTAINER =		Sebastian Reitenbach <sebastia@openbsd.org>

# LGPL 3.0
PERMIT_PACKAGE =	Yes

MODULES =		lang/python
MODPY_PYBUILD =		flit_core
MODPY_PI =		Yes

FLAVORS =		python3
FLAVOR =		python3

.include <bsd.port.mk>
