MODPY_EGG_VERSION =	5.0.3
TRYTON_MODULE =		account_stock_landed_cost_weight

TRYTON_DEPENDS +=	account_stock_landed_cost \
			product \
			product_measurements \
			stock_shipment_measurements

.include <bsd.port.mk>
