# $OpenBSD: Makefile,v 1.2 2010/09/24 08:01:46 jasper Exp $

COMMENT =	rewrite strings based on a set of known prefixes

DISTNAME =	String-RewritePrefix-0.005
CATEGORIES =	textproc
MODULES =	cpan

# Perl
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

RUN_DEPENDS =	::devel/p5-Sub-Exporter

.include <bsd.port.mk>
