# $OpenBSD: Makefile,v 1.7 2016/03/20 19:57:07 naddy Exp $

COMMENT =		simple and pure Perl RSS parser

DISTNAME =		RSS-Parser-Lite-0.12
CATEGORIES =		textproc

# perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan
PKG_ARCH =		*

CPAN_AUTHOR =		TFPBL

RUN_DEPENDS =		www/p5-SOAP-Lite \
			textproc/p5-XML-Parser-Lite

.include <bsd.port.mk>
