COMMENT =	visitor-style traversal of Perl data structures

DISTNAME =	Data-Visitor-0.32
FIX_EXTRACT_PERMISSIONS = Yes

CATEGORIES =	devel

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Moose>=0.89 \
			devel/p5-Tie-ToObject>=0.01 \
			devel/p5-namespace-clean>=0.19
TEST_DEPENDS =		devel/p5-Test-Needs

PKG_ARCH =		*

.include <bsd.port.mk>
