# $OpenBSD: intltool.port.mk,v 1.3 2010/11/20 19:56:48 espie Exp $

BUILD_DEPENDS+=	textproc/intltool

MODINTLTOOL_OVERRIDE=INTLTOOL_EXTRACT=${LOCALBASE}/bin/intltool-extract \
		INTLTOOL_MERGE=${LOCALBASE}/bin/intltool-merge \
		INTLTOOL_UPDATE=${LOCALBASE}/bin/intltool-update

CONFIGURE_ENV+=	${MODINTLTOOL_OVERRIDE}
MAKE_ENV+=	${MODINTLTOOL_OVERRIDE}
MAKE_FLAGS+=	${MODINTLTOOL_OVERRIDE}
