# $OpenBSD: Makefile,v 1.8 2020/10/13 10:26:34 sthen Exp $

COMMENT-main =	Java servlet 4.0 and Java server pages 2.3 server
PKGSPEC-main =	tomcat->=9,<10

MAJ_VER =	9
MIN_VER =	0
MICRO_VER =	39

.include <bsd.port.mk>
