# $OpenBSD: Makefile,v 1.5 2010/04/15 13:56:34 ajacoutot Exp $

COMMENT=	generate SQL from Perl data structures

MODULES=	cpan
DISTNAME=	SQL-Abstract-1.22
PKGNAME=	p5-${DISTNAME}p0
CATEGORIES=	databases
EXTRACT_SUFX=	.tgz

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
