# $OpenBSD: modules.inc,v 1.2 2022/03/07 18:03:30 abieber Exp $

MODGO_MODULES =	\
	github.com/creack/pty		 v1.1.15 \
	github.com/frankban/quicktest	 v1.13.1 \
	github.com/google/go-cmp	 v0.5.6 \
	github.com/google/renameio	 v1.0.1 \
	github.com/kr/pretty		 v0.3.0 \
	github.com/kr/pty		 v1.1.1 \
	github.com/kr/text		 v0.2.0 \
	github.com/pkg/diff		 v0.0.0-20210226163009-20ebb0f2a09e \
	github.com/rogpeppe/go-internal	 v1.8.1-0.20210923151022-86f73c517451 \
	golang.org/x/sync		 v0.0.0-20210220032951-036812b2e83c \
	golang.org/x/sys		 v0.0.0-20210925032602-92d5a993a665 \
	golang.org/x/term		 v0.0.0-20210916214954-140adaaadfaf \
	golang.org/x/xerrors		 v0.0.0-20191204190536-9bdfabe68543 \
	gopkg.in/check.v1		 v1.0.0-20180628173108-788fd7840127 \
	gopkg.in/errgo.v2		 v2.1.0 \
	mvdan.cc/editorconfig		 v0.2.0

MODGO_MODFILES =	\
	github.com/creack/pty		 v1.1.9 \
	github.com/kr/pretty		 v0.1.0 \
	github.com/kr/text		 v0.1.0 \
	github.com/rogpeppe/go-internal	 v1.6.1 \
	golang.org/x/sys		 v0.0.0-20210615035016-665e8c7367d1

