# OpenBSD makefile for:		  dialog 
# Version required:     	  0.6z
# Date created:			  12 November 1998
# Whom:				  Yannick Cote 
#
# $OpenBSD: Makefile,v 1.3 2000/03/22 19:58:12 turan Exp $
#

DISTNAME= 	dialog-0.6z	
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_SUNSITE} 
MASTER_SITE_SUBDIR= utils/shell

MAINTAINER=     yanick@fries.net

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

USE_GMAKE=		YES

.include <bsd.port.mk>
