# $OpenBSD: Makefile,v 1.8 2015/01/21 14:19:14 sthen Exp $

COMMENT=	calculate precision, recall, F1, accuracy, etc
DISTNAME =	Statistics-Contingency-0.09
CATEGORIES=	math

# Perl
PERMIT_PACKAGE_CDROM=	Yes

RUN_DEPENDS=		devel/p5-Params-Validate>=0.23

CONFIGURE_STYLE=	modbuild

MODULES=		cpan

.include <bsd.port.mk>
