# $OpenBSD: Makefile,v 1.4 2001/12/24 07:51:06 mark Exp $

COMMENT=	"interactive utility that displays info about online users"

DISTNAME=	whowatch-1.4
CATEGORIES=	sysutils
NEED_VERSION=	1.364
MASTER_SITES=	http://wizard.ae.krakow.pl/~mike/download/ \
		http://janek.ae.krakow.pl/~suszyckm/download/

HOMEPAGE=	http://wizard.ae.krakow.pl/~mike/

MAINTAINER=	Mark Grimes <mark@openbsd.org>

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE= gnu dest

.include <bsd.port.mk>
