COMMENT=		assert performance of perl regexps

MODULES=		cpan
DISTNAME =		Devel-SawAmpersand-0.33
CATEGORIES=		devel
REVISION =		2

# perl
PERMIT_PACKAGE=	Yes

WANTLIB += c perl

.include <bsd.port.mk>
