# $OpenBSD: Makefile,v 1.5 2016/06/30 11:48:25 espie Exp $

COMMENT =	fancy forms fields
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	compact_forms-6.x-1.3
PKGNAME =	drupal6-compact-forms-1.3
REVISION =	1

.include <bsd.port.mk>
