# $OpenBSD: Makefile,v 1.14 2019/05/07 17:54:23 cwen Exp $

COMMENT=	remove files and directories with perl

MODULES=	cpan
PKG_ARCH=	*

DISTNAME=	File-Remove-1.58
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes

CONFIGURE_STYLE=	modbuild

.include <bsd.port.mk>
