# $OpenBSD: Makefile,v 1.13 2015/01/21 14:27:58 sthen Exp $

COMMENT=	abstraction layer for logging and tracing

MODULES=	cpan
DISTNAME=	Log-Agent-1.000
CATEGORIES=	devel

# Artistic License
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
