.\"	$OpenBSD: link-checksums.1,v 1.1 2010/09/13 11:31:42 espie Exp $
.\"
.\" Copyright (c) 2010 Marc Espie <espie@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: September 13 2010 $
.Dt LINK-CHECKSUMS 1
.Os
.Sh NAME
.Nm link-checksums
.Nd creates by-cipher links for distfiles
.Sh SYNOPSIS
.Nm link-checksums
.Sh DESCRIPTION
.Nm
is a helper script for use within
.Pa /usr/ports/distfiles
for people running distfiles mirrors.
.Pp
.Nm
will create hardlinks between distfiles and corresponding checksums;
those will in turn be used by the ports infrastructure, when running
.Sq make fetch REFETCH=true .
.Pp
.Nm
scans directory
.Ev DISTDIR
.Po
by default,
.Pa /usr/ports/distfiles
.Pc
and creates hardlinks for each checksum algorithm in
.Ev CIPHERS
(by default, sha1 md5 rmd160 sha256),
such as
.Pa by_cipher/md5/8506fd205028a96c741e4037de6e3c42 .
.Sh SEE ALSO
.Xr cksum 1 ,
.Xr bsd.port.mk 5 ,
.Xr mirroring-ports 7 .
