MODWLROOTS_VERSION =		0.19

MODWLROOTS_WANTLIB =		wlroots-${MODWLROOTS_VERSION}
MODWLROOTS_LIB_DEPENDS =    	wayland/wlroots

MODWLROOTS_LIBDEP?=		Yes

.if ${MODWLROOTS_LIBDEP:L} == "yes"
LIB_DEPENDS +=			${MODWLROOTS_LIB_DEPENDS}
WANTLIB +=              	${MODWLROOTS_WANTLIB}
.endif

SUBST_VARS += 			MODWLROOTS_VERSION
