VERSION =	2.54
REVISION = 	6

BUILD_DEPENDS =		devel/help2man

CONFIGURE_STYLE =	gnu
CONFIGURE_ARGS +=	--without-lispdir
MODGNU_CONFIG_GUESS_DIRS=${WRKSRC}/config

NO_TEST=		Yes

.include <bsd.port.mk>
