MODGO_MODULES =	\
	github.com/chzyer/logex						 v1.1.10 \
	github.com/chzyer/readline					 v0.0.0-20180603132655-2972be24d48e \
	github.com/chzyer/test						 v0.0.0-20180213035817-a1ea475d72b1 \
	github.com/davecgh/go-spew					 v1.1.1 \
	github.com/facette/natsort					 v0.0.0-20181210072756-2cd4dd1e2dcb \
	github.com/felixge/fgprof					 v0.9.3 \
	github.com/google/pprof						 v0.0.0-20211214055906-6f57359322fd \
	github.com/ianlancetaylor/demangle				 v0.0.0-20210905161508-09a460cdf81d \
	github.com/johnkerl/lumin					 v1.0.0 \
	github.com/kballard/go-shellquote				 v0.0.0-20180428030007-95032a82bc51 \
	github.com/klauspost/compress					 v1.17.7 \
	github.com/lestrrat-go/envload					 v0.0.0-20180220234015-a3eb8ddeffcc \
	github.com/lestrrat-go/strftime					 v1.0.6 \
	github.com/mattn/go-isatty					 v0.0.20 \
	github.com/nine-lives-later/go-windows-terminal-sequences	 v1.0.4 \
	github.com/pkg/errors						 v0.9.1 \
	github.com/pkg/profile						 v1.7.0 \
	github.com/pmezard/go-difflib					 v1.0.0 \
	github.com/stretchr/objx					 v0.5.2 \
	github.com/stretchr/testify					 v1.9.0 \
	golang.org/x/mod						 v0.8.0 \
	golang.org/x/sys						 v0.18.0 \
	golang.org/x/term						 v0.18.0 \
	golang.org/x/text						 v0.14.0 \
	golang.org/x/tools						 v0.6.0 \
	gopkg.in/check.v1						 v0.0.0-20161208181325-20d25e280405 \
	gopkg.in/yaml.v3						 v3.0.1

MODGO_MODFILES =	\
	github.com/davecgh/go-spew	 v1.1.0 \
	github.com/stretchr/objx	 v0.1.0 \
	github.com/stretchr/objx	 v0.4.0 \
	github.com/stretchr/testify	 v1.3.0 \
	github.com/stretchr/testify	 v1.7.1 \
	github.com/stretchr/testify	 v1.8.0 \
	golang.org/x/sys		 v0.0.0-20211007075335-d3039528d8ac \
	golang.org/x/sys		 v0.5.0 \
	golang.org/x/sys		 v0.6.0 \
	gopkg.in/yaml.v3		 v3.0.0-20200313102051-9f266ea9e77c

