.\"	$OpenBSD: sqlports.5,v 1.2 2020/07/05 12:28:13 espie Exp $
.\"
.\" Copyright (c) 2020 Marc Espie <espie@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: July 5 2020 $
.Dt SQLPORTS 5
.Os
.Sh NAME
.Nm sqlports
.Nd sqlite database for ports meta information
.Sh DESCRIPTION
.Nm
is built as a port by parsing the output of
.Li make dump-vars
over the full ports tree.
.Pp
The database contains tables for automated tools, along with nice views
for human consumption.
Tables are as follows:
.Bl -tag -offset indent -width keyword
.It _Paths (ID, FULLPKGPATH, PKGPATH, CANONICAL)
PKGPATH points to a PATHS entry corresponding to the stripped down version of 
FULLPKGPATH, without flavors or subpackage markers, or is null if FULLPKGPATH
is already stripped.  
Every other FULLPKGPATH, PKGPATH, DEPENDSPATH entry
in the database points to this table.
The FULLPKGPATH is complete, including flavors and pseudo flavors markers. 
For every port with MULTI_PACKAGES settings, one entry is written 
for each SUBPACKAGE.
CANONICAL points to the actual ID to use as an entry in other tables, for
FULLPKGPATH which don't have their own entry.
.It _Ports(FULLPKGPATH, ...)
holds all the information retrieved through various variables that is not
stored in specialized tables, e.g.,:
.Bl -tag -width AUTOMAKE_VERSION -offset indent -compact
.It AUTOCONF_VERSION 
.It AUTOMAKE_VERSION 
.It COMES_WITH
.It COMMENT 
.It COMPILER
.It COMPILER_LANGS
.It DISTFILES 
.It DISTNAME 
.It DIST_SUBDIR 
.It EPOCH
.It FIX_EXTRACT_PERMISSIONS
.It FULLPKGNAME
.It GH_*
.It HOMEPAGE 
.It IGNORE
.It IS_INTERACTIVE 
.It MAINTAINER
.It NO_*
.It PATCHFILES
.It PERMIT_*
.It PKGNAME 
.It PKGSPEC
.It PKGSTEM
.It PKG_ARCH 
.It PORTROACH
.It PORTROACH_COMMENT
.It PREFIX
.It PSEUDO_FLAVOR
.It REVISION
.It SEPARATE_BUILD
.It STATIC_PLIST
.It SUBPACKAGE
.It SUPDISTFILES
.It TEST_IS_INTERACTIVE 
.It UPDATE_PLIST_ARGS
.It USE_*
.El
.It _Flavors(FULLPKGPATH, VALUE, N)
.It _PseudoFlavors(FULLPKGPATH, VALUE, N)
.It _Categories(FULLPKGPATH, VALUE, N)
.It _Multi(FULLPKGPATH, VALUE, SUBPKGPATH, N)
.It _Modules(FULLPKGPATH, VALUE, N)
.It _Configure(FULLPKGPATH, VALUE, N)
.It _ConfigureArgs(FULLPKGPATH, VALUE, N, QUOTETYPE)
.It _MasterSites(FULLPKGPATH, N, VALUE)
.It _Makefiles(FULLPKGPATH, VALUE, N)
.It _NotForArch(FULLPKGPATH, VALUE, N)
.It _OnlyForArch(FULLPKGPATH, VALUE, N)
.El
.Sh FILES
.Pa ${TRUEPREFIX}/share/sqlports
.Sh SEE ALSO
.Xr sqlite3 1
