MODGO_MODULES =	\
	github.com/adrg/xdg		 v0.5.3 \
	github.com/alecthomas/assert/v2	 v2.11.0 \
	github.com/alecthomas/chroma/v2	 v2.22.0 \
	github.com/alecthomas/repr	 v0.5.2 \
	github.com/charlievieth/strcase	 v0.0.6 \
	github.com/creack/pty		 v1.1.24 \
	github.com/davecgh/go-spew	 v1.1.1 \
	github.com/dlclark/regexp2	 v1.11.5 \
	github.com/go-enry/go-enry/v2	 v2.9.6 \
	github.com/go-enry/go-oniguruma	 v1.2.1 \
	github.com/google/go-cmp	 v0.7.0 \
	github.com/hexops/gotextdiff	 v1.0.3 \
	github.com/klauspost/compress	 v1.19.1 \
	github.com/pmezard/go-difflib	 v1.0.0 \
	github.com/rivo/uniseg		 v0.4.7 \
	github.com/sirupsen/logrus	 v1.9.4 \
	github.com/stretchr/objx	 v0.5.0 \
	github.com/stretchr/testify	 v1.10.0 \
	github.com/ulikunitz/xz		 v0.5.16 \
	golang.org/x/mod		 v0.12.0 \
	golang.org/x/sync		 v0.22.0 \
	golang.org/x/sys		 v0.47.0 \
	golang.org/x/term		 v0.45.0 \
	golang.org/x/tools		 v0.13.0 \
	gopkg.in/check.v1		 v0.0.0-20161208181325-20d25e280405 \
	gopkg.in/yaml.v2		 v2.2.8 \
	gopkg.in/yaml.v3		 v3.0.1 \
	gotest.tools/v3			 v3.5.2

MODGO_MODFILES =	\
	github.com/davecgh/go-spew	 v1.1.0 \
	github.com/google/go-cmp	 v0.5.9 \
	github.com/stretchr/objx	 v0.1.0 \
	github.com/stretchr/objx	 v0.4.0 \
	github.com/stretchr/testify	 v1.7.1 \
	github.com/stretchr/testify	 v1.8.0 \
	github.com/stretchr/testify	 v1.8.1 \
	github.com/stretchr/testify	 v1.9.0 \
	golang.org/x/sys		 v0.12.0 \
	golang.org/x/sys		 v0.13.0 \
	golang.org/x/sys		 v0.26.0 \
	golang.org/x/sys		 v0.30.0 \
	gopkg.in/yaml.v3		 v3.0.0-20200313102051-9f266ea9e77c

