# $OpenBSD: Makefile,v 1.14 2019/07/12 21:02:17 sthen Exp $

COMMENT=	sort perl arrays
CATEGORIES=	devel
DISTNAME =	Sort-Key-1.33
MODULES=	cpan

# perl
PERMIT_PACKAGE=	Yes

WANTLIB += c perl

.include <bsd.port.mk>
