# $OpenBSD: Makefile,v 1.2 2007/09/16 02:53:08 merdely Exp $

SHARED_ONLY=	Yes
COMMENT=	sort perl arrays
CATEGORIES=	devel
DISTNAME=	Sort-Key-1.28
MODULES=	cpan

# perl
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
