#!/bin/sh
# $OpenBSD: DEINSTALL,v 1.1 2000/08/12 08:17:57 brad Exp $
#
# Imlib de-installation

set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
CONFIG_DIR=/etc

echo
echo "+---------------"
echo "| To completely deinstall the $1 package you need to perform"
echo "| this step as root:"
echo "|"
echo "|           rm -f $CONFIG_DIR/imrc"
echo "|           rm -f $CONFIG_DIR/im_palette.pal"
echo "|"
echo "| Do not do this if you plan on re-installing $1"
echo "| at some future time."
echo "+---------------"
echo

exit 0
