# $OpenBSD: Makefile,v 1.4 2019/07/12 20:45:06 sthen Exp $

COMMENT =		temporary buffer to save bytes

MODULES =		cpan
PKG_ARCH =		*
DISTNAME =		Stream-Buffered-0.03
CATEGORIES =		devel
REVISION =		0

# Perl
PERMIT_PACKAGE =	Yes

.include <bsd.port.mk>
