# $OpenBSD: Makefile,v 1.4 2013/03/11 10:50:09 espie Exp $

COMMENT=		JSON implementation in C

DISTNAME=		json-c-0.9
CATEGORIES=		devel
SHARED_LIBS +=  json                 1.1      # .0.1

HOMEPAGE=		http://oss.metaparadigm.com/json-c/

# MIT
PERMIT_PACKAGE_CDROM=	Yes

MASTER_SITES=		${HOMEPAGE}

CONFIGURE_STYLE=	gnu
USE_LIBTOOL=		Yes

.include <bsd.port.mk>
