# $OpenBSD: Makefile,v 1.1.1.1 2012/05/10 13:15:46 jasper Exp $

COMMENT =	TDD framework for node.js

NPM_VERSION =	0.9.2
NPM_NAME =	expresso
CATEGORIES =	devel

HOMEPAGE =	http://visionmedia.github.com/expresso/

# MIT
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		www/node

CONFIGURE_STYLE =	npm

.include <bsd.port.mk>
