# $OpenBSD: Makefile,v 1.8 2008/10/03 10:30:30 jasper Exp $

COMMENT=	error/exception handling in an OO-ish way

MODULES=	cpan
DISTNAME=	Error-0.17015
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
