# $OpenBSD: Makefile,v 1.3 2010/12/03 11:45:42 ajacoutot Exp $

COMMENT =	parse, manipulate and lookup IPv4 CIDR blocks

MODULES =	cpan
DISTNAME =	Net-Netmask-1.9015
REVISION =	0
CATEGORIES =	net
USE_GROFF =	Yes

MAINTAINER =	Toni Mueller <support@oeko.net>

# custom
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

.include <bsd.port.mk>
