# $OpenBSD: Makefile,v 1.42 2001/02/04 18:56:17 reinhard Exp $
# $FreeBSD: Makefile,v 1.40 1997/11/16 22:49:20 fenner Exp $
#

     SUBDIR += ac3dec
     SUBDIR += aumix
     SUBDIR += bladeenc
     SUBDIR += cdparanoia
#    SUBDIR += cam
#    SUBDIR += cddbd
#    SUBDIR += cdplay
     SUBDIR += esound
#    SUBDIR += gmod
     SUBDIR += gogo
     SUBDIR += gom
     SUBDIR += gqmpeg
     SUBDIR += gsm
     SUBDIR += knapster
     SUBDIR += lame
     SUBDIR += libcdaudio
     SUBDIR += lopster
#    SUBDIR += maplay
#    SUBDIR += mikmod
     SUBDIR += mp3cddb
     SUBDIR += mp3encode
     SUBDIR += mp3info
     SUBDIR += mpegaudio
     SUBDIR += mpg123
#    SUBDIR += mxv
     SUBDIR += nap
#    SUBDIR += nas
     SUBDIR += nspmod
     SUBDIR += opennap
     SUBDIR += p5-Audio-CD
     SUBDIR += p5-MP3-ID3v1Tag
     SUBDIR += p5-MP3-Info
     SUBDIR += p5-cddb
#    SUBDIR += playmidi
#    SUBDIR += radio
     SUBDIR += rio500
#    SUBDIR += rosegarden
     SUBDIR += rplay
     SUBDIR += rsynth
#    SUBDIR += s3mod
     SUBDIR += sox
#    SUBDIR += splay
     SUBDIR += teknap
     SUBDIR += timidity
     SUBDIR += tosha
     SUBDIR += tracker
     SUBDIR += waveplay
     SUBDIR += workman
     SUBDIR += wsoundprefs
     SUBDIR += wsoundserver
     SUBDIR += wsoundserver:esd
     SUBDIR += xcd
     SUBDIR += xcdplayer
     SUBDIR += xmcd
     SUBDIR += xmix
     SUBDIR += xmmix
     SUBDIR += xmp

.include <bsd.port.subdir.mk>
