# $OpenBSD: Makefile,v 1.1.1.1 2014/03/16 21:49:43 afresh1 Exp $

COMMENT =	locate (written) numbers in English text
DISTNAME =	Lingua-EN-FindNumber-1.2
CATEGORIES =	textproc

MAINTAINER =	Andrew Fresh <andrew@cpan.org>

# same terms as Perl itself
PERMIT_PACKAGE_CDROM =	Yes

MODULES =	cpan
RUN_DEPENDS =	textproc/p5-Lingua-EN-Words2Nums

.include <bsd.port.mk>
