# $OpenBSD: Makefile,v 1.7 2016/03/20 19:56:08 naddy Exp $

COMMENT =	shim to support either v1 or v2 APIs of JSON::XS

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	JSON-XS-VersionOneAndTwo-0.31
REVISION =	1
CATEGORIES =	converters

# Perl
PERMIT_PACKAGE_CDROM =	Yes

RUN_DEPENDS =	converters/p5-JSON-XS

.include <bsd.port.mk>
