# $OpenBSD: Makefile,v 1.11 2013/03/11 10:50:13 espie Exp $

COMMENT =	Carp for clan of modules

MODULES =	cpan
DISTNAME =	Carp-Clan-6.04
REVISION =	0
CATEGORIES =	devel
USE_GROFF =	Yes

MAINTAINER =	Kevin Lo <kevlo@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

RUN_DEPENDS=		devel/p5-Test-Exception

.include <bsd.port.mk>
