MODGO_MODULES =	\
	github.com/davecgh/go-spew	 v1.1.1 \
	github.com/fsnotify/fsnotify	 v1.7.0 \
	github.com/golang/freetype	 v0.0.0-20170609003504-e2365dfdc4a0 \
	github.com/google/go-cmp	 v0.6.0 \
	github.com/jezek/xgb		 v1.1.1 \
	github.com/yuin/goldmark	 v1.4.13 \
	golang.org/x/crypto		 v0.24.0 \
	golang.org/x/exp		 v0.0.0-20240325151524-a685a6edb6d8 \
	golang.org/x/image		 v0.18.0 \
	golang.org/x/mod		 v0.18.0 \
	golang.org/x/net		 v0.26.0 \
	golang.org/x/sync		 v0.7.0 \
	golang.org/x/sys		 v0.21.0 \
	golang.org/x/telemetry		 v0.0.0-20240521205824-bda55230c457 \
	golang.org/x/term		 v0.21.0 \
	golang.org/x/text		 v0.16.0 \
	golang.org/x/tools		 v0.22.0

MODGO_MODFILES =	\
	github.com/google/go-cmp	 v0.5.8 \
	golang.org/x/mod		 v0.16.0 \
	golang.org/x/mod		 v0.17.0 \
	golang.org/x/sys		 v0.4.0 \
	golang.org/x/tools		 v0.13.0 \
	golang.org/x/tools		 v0.19.0 \
	golang.org/x/tools		 v0.21.1-0.20240508182429-e35e4ccd0d2d

