# $OpenBSD: Makefile,v 1.6 2017/04/13 13:40:21 sthen Exp $

ADDON_NAME =		noscript
V =			2.9.5.3
REVISION =		0
COMMENT =		Tor Browser add-on: flexible JS blocker
HOMEPAGE =		http://noscript.net
MASTER_SITES =		https://secure.informaction.com/download/releases/
GUID =			{73a6fe31-595d-460b-a920-fcc0f8843232}
DISTFILE_IS_XPI =	Yes

.include <bsd.port.mk>
