ADDON_NAME =		noscript
V =			13.5.7.1984
COMMENT =		Tor Browser add-on: flexible JS blocker
HOMEPAGE =		https://noscript.net
SITES =			https://dist.torproject.org/torbrowser/noscript/
GUID =			{73a6fe31-595d-460b-a920-fcc0f8843232}
DISTFILE_IS_XPI =	Yes

.include <bsd.port.mk>
