# $OpenBSD: Makefile,v 1.24 2020/07/02 17:50:45 jasper Exp $

ADDON_NAME =		noscript
V =			11.0.32
COMMENT =		Tor Browser add-on: flexible JS blocker
HOMEPAGE =		https://noscript.net
MASTER_SITES =		https://secure.informaction.com/download/releases/
GUID =			{73a6fe31-595d-460b-a920-fcc0f8843232}
DISTFILE_IS_XPI =	Yes

.include <bsd.port.mk>
