COMMENT =		identity management for flask

MODPY_EGG_VERSION =	0.4.0
DISTNAME =		Flask-Principal-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME:L}
REVISION =		7

CATEGORIES =		www

HOMEPAGE =		https://pythonhosted.org/Flask-Principal/

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

FLAVORS =		python3
FLAVOR  =		python3

MODPY_PI =		Yes
MODPY_PYBUILD =		setuptools

RUN_DEPENDS =		www/py-flask${MODPY_FLAVOR}

.include <bsd.port.mk>
