COMMENT =		canonical JSON

MODPY_EGG_VERSION =	2.0.0
DISTNAME =		canonicaljson-${MODPY_EGG_VERSION}
PKGNAME =		py-canonicaljson-${MODPY_EGG_VERSION}
REVISION =		0

CATEGORIES =		textproc

HOMEPAGE =		https://github.com/matrix-org/python-canonicaljson

MAINTAINER =		Renaud Allard <renaud@allard.it>

# Apache-2.0
PERMIT_PACKAGE =	Yes

MODULES =		lang/python
MODPY_PYBUILD =		setuptools
MODPY_PI =		Yes
FLAVORS =		python3
FLAVOR =		python3

.include <bsd.port.mk>
