COMMENT =		pure-Python HTTP/2 framing

MODPY_DISTV =	6.0.1
DISTNAME =		hyperframe-${MODPY_DISTV}
PKGNAME =		py-${DISTNAME}
REVISION =		0

CATEGORIES =		www

# MIT
PERMIT_PACKAGE	=	Yes

MODULES =		lang/python

HOMEPAGE =		https://github.com/python-hyper/hyperframe

MODPY_PI =		Yes
MODPY_PYBUILD =		setuptools

.include <bsd.port.mk>
