# $OpenBSD: Makefile,v 1.6 2012/01/26 13:18:16 pascal Exp $

     SUBDIR =
     SUBDIR += 3.3
#     SUBDIR += 3.4
#     SUBDIR += 4.0
#     SUBDIR += 4.1
     SUBDIR += 4.2
#     SUBDIR += 4.3
     SUBDIR += 4.6

.include <bsd.port.subdir.mk>
