# $OpenBSD: Makefile,v 1.3 2013/12/30 11:25:22 landry Exp $

SUBDIR =
SUBDIR += connectagram
SUBDIR += cutemaze
SUBDIR += hexalate
SUBDIR += peg-e
SUBDIR += simsu
SUBDIR += tanglet
SUBDIR += tetzle

.include <bsd.port.subdir.mk>
