# $OpenBSD: Makefile,v 1.3 2010/04/15 13:56:34 ajacoutot Exp $

COMMENT= 	automates the Factory design pattern


MODULES=	cpan

DISTNAME=	Class-Factory-1.02
PKGNAME=	p5-${DISTNAME}p0
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
