# $OpenBSD: Makefile,v 1.15 2004/04/22 22:15:47 naddy Exp $

COMMENT=	"library to parse Uniform Resource Identifiers"

DISTNAME=	URI-1.30
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	www perl5

MASTER_SITES=	${MASTER_SITE_PERL_CPAN:=URI/}

MAINTAINER=	Jim Geovedi <jim@corebsd.or.id>

# GPL/Artistic licence
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE=perl

.include <bsd.port.mk>
