# $OpenBSD: Makefile,v 1.8 2016/06/29 08:11:28 ajacoutot Exp $

MODPY_EGG_VERSION =	3.2.2

TRYTOND_MODULE =	bank
REVISION =		1

RUN_DEPENDS =		devel/py-stdnum \
			productivity/tryton/currency \
			productivity/tryton/party

.include <bsd.port.mk>
