COMMENT=		low-level, pure Python DBus protocol wrapper

MODPY_EGG_VERSION=	0.8.0
DISTNAME=		jeepney-${MODPY_EGG_VERSION}
PKGNAME=		py-${DISTNAME}
REVISION=		0

CATEGORIES=		devel

HOMEPAGE=		https://gitlab.com/takluyver/jeepney

# MIT
PERMIT_PACKAGE=		Yes

MODULES=		lang/python

MODPY_PI=		Yes
MODPY_PYBUILD=		flit_core

FLAVORS=		python3
FLAVOR=			python3

.include <bsd.port.mk>
