.\"	$OpenBSD: crossfire.1,v 1.1.1.1 2020/05/14 20:34:19 ian Exp $
.\"
.\" Copyright (c) 2020 Ian Darwin
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\" The following requests are required for all man pages.
.\"
.Dd $Mdocdate: May 14 2020 $
.Dt crossfire 1
.Os
.Sh NAME
.Nm crossfire
.Nd crossword puzzle constructor's tool
.Sh SYNOPSIS
.\" For a program:  program [-abc] file ...
.Nm crossfire
.Sh DESCRIPTION
.Nm
is a portable, professional-grade crossword puzzle construction tool.
.Sh FILES
.Pa ~/crossfire/default.dict - default dictionary
.Sh SEE ALSO
See
.Lk https://www.nytimes.com/2018/09/14/crosswords/how-to-make-a-crossword-puzzle-the-series.html
for general information on crossword-making, and a writeup of this 
program in part 2.
.Sh HISTORY
See
.Lk http://beekeeperlabs.com/crossfire/versions.html
.Sh CAVEATS
CrossFire will run in demo mode until you install a license token.
