# $OpenBSD: Makefile,v 1.29 2017/05/08 19:41:11 jasper Exp $

COMMENT=	Scalable Vector Graphics (SVG) in perl

DISTNAME=	SVG-2.75
CATEGORIES=	graphics devel

MAINTAINER=	Jasper Lievisse Adriaanse <jasper@openbsd.org>

# perl
PERMIT_PACKAGE_CDROM=	Yes

MODULES=		cpan
PKG_ARCH=		*

MODCPAN_EXAMPLES=	Yes
MODCPAN_EG_DIR=		examples

.include <bsd.port.mk>
