# $OpenBSD: Makefile,v 1.13 2010/04/04 13:08:48 jasper Exp $

COMMENT=	Scalable Vector Graphics (SVG) in perl

DISTNAME=	SVG-2.49
PKGNAME=	p5-${DISTNAME}p0
CATEGORIES=	graphics devel

MAINTAINER=	Jasper Lievisse Adriaanse <jasper@openbsd.org>

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=	cpan

.include <bsd.port.mk>
