# $OpenBSD: Makefile,v 1.12 2015/01/16 09:59:20 ajacoutot Exp $

MODPY_EGG_VERSION =	3.2.1

TRYTOND_MODULE =	sale_opportunity

RUN_DEPENDS =		productivity/tryton/account \
			productivity/tryton/company \
			productivity/tryton/currency \
			productivity/tryton/party \
			productivity/tryton/product \
			productivity/tryton/sale \
			productivity/tryton/stock

.include <bsd.port.mk>
