.\"     $OpenBSD: idea.1,v 1.3 2018/04/14 07:08:14 rsadowski Exp $
.Dd $Mdocdate: April 14 2018 $
.Dt IDEA 1
.Os
.Sh NAME
.Nm idea
.Nd launch IntelliJ IDEA Java Integrated Development Environment
.Sh SYNOPSIS
.Nm
.Op jvm-args
.Sh DESCRIPTION
.Nm
starts up the IntelliJ IDEA Community Edition Java Integrated
Development Environment.
.Sh SEE ALSO
.Lk https://www.jetbrains.com/idea/
