.Dd $Mdocdate: March 11 2022 $
.Dt IDEA 1
.Os
.Sh NAME
.Nm idea
.Nd launch IntelliJ IDEA Java Integrated Development Environment
.Sh SYNOPSIS
.Nm
.Op jvm-args
.Sh DESCRIPTION
.Nm
starts up the IntelliJ IDEA Community Edition Java Integrated
Development Environment.
.Sh SEE ALSO
.Lk https://www.jetbrains.com/idea/
