.\"     $OpenBSD: idea.1,v 1.1.1.1 2010/04/09 22:23:26 ian Exp $
.Dd $Mdocdate: April 9 2010 $
.Dt IDEA 1
.Os
.Sh NAME
.Nm idea
.Nd launch IntelliJ IDEA Java Integrated Development Environment
.Sh SYNOPSIS
.Nm
.Op jvm-args
.Sh DESCRIPTION
.Nm
starts up the IntelliJ IDEA Community Edition Java Integrated
Development Environment.
.Sh SEE ALSO
The web site
http://www.jetbrains.com/idea/.
