# $OpenBSD: Makefile,v 1.8 2015/11/05 19:08:56 jca Exp $

COMMENT=        generate Perl class hierarchies

MODULES=	cpan
DISTNAME=	Class-Generate-1.14
CATEGORIES=     devel
REVISION=	0

# Perl
PERMIT_PACKAGE_CDROM=	Yes

CONFIGURE_STYLE=	modbuild

.include <bsd.port.mk>
