MODGO_MODULES =	\
	github.com/fatih/color		 v1.12.0 \
	github.com/google/go-jsonnet	 v0.20.0 \
	github.com/mattn/go-colorable	 v0.1.8 \
	github.com/mattn/go-isatty	 v0.0.12 \
	github.com/sergi/go-diff	 v1.1.0 \
	golang.org/x/sys		 v0.1.0 \
	gopkg.in/check.v1		 v0.0.0-20161208181325-20d25e280405 \
	gopkg.in/yaml.v2		 v2.4.0 \
	sigs.k8s.io/yaml		 v1.1.0

MODGO_MODFILES =	\
	gopkg.in/yaml.v2	 v2.2.7

