# $OpenBSD: Makefile,v 1.11 2010/12/03 11:46:47 ajacoutot Exp $

SHARED_ONLY=	Yes

COMMENT=	module to calculate Nilsimsa digests

MODULES=	cpan
DISTNAME=	Digest-Nilsimsa-0.06
REVISION=	2
CATEGORIES=	security
USE_GROFF =	Yes

# Artistic licence
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
