# $OpenBSD: Makefile,v 1.3 2010/12/03 11:46:53 ajacoutot Exp $

COMMENT=	Perl extension for minifying JavaScript code

MODULES=	cpan
DISTNAME=	JavaScript-Minifier-1.05
REVISION=	0
CATEGORIES=	www
USE_GROFF =	Yes

MAINTAINER=	Girish Venkatachalam <girish1729@gmail.com>

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MAKE_ENV=	TEST_POD=Yes

.include <bsd.port.mk>
