COMMENT =	tool for compiling Ruby native extensions

DISTNAME =	pkg-config-1.5.1
CATEGORIES =	devel

# LGPL V2+
PERMIT_PACKAGE =	Yes

MODULES =		lang/ruby

CONFIGURE_STYLE =	gem

.include <bsd.port.mk>
