# $OpenBSD: Makefile,v 1.4 2016/03/20 19:56:41 naddy Exp $

COMMENT=	tiny pure-perl UUID generation

MODULES=	cpan
PKG_ARCH=	*
DISTNAME =	UUID-Tiny-1.04
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=   Yes

MAKE_ENV+=	TEST_POD=1

.include <bsd.port.mk>
