# $OpenBSD: Makefile,v 1.9 2019/05/04 01:18:59 danj Exp $

COMMENT=		FTP client class with automatic reconnect on failure

MODULES=		cpan
PKG_ARCH=		*
DISTNAME =		Net-FTP-AutoReconnect-0.3
CATEGORIES=		net
REVISION=		0

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
