.Dd $Mdocdate: March 11 2022 $
.Dt PYCHARM 1
.Os
.Sh NAME
.Nm pycharm
.Nd launch PyCharm Python Integrated Development Environment
.Sh SYNOPSIS
.Nm
.Op jvm-args
.Sh DESCRIPTION
.Nm
starts up the JetBrains PyCharm Community Edition Python Integrated
Development Environment.
.Sh SEE ALSO
The web site
.Lk https://www.jetbrains.com/pycharm/ .
