.\"     $OpenBSD: pycharm.1,v 1.1 2018/05/27 17:09:44 rsadowski Exp $
.Dd $Mdocdate: May 27 2018 $
.Dt PYCHARM 1
.Os
.Sh NAME
.Nm pycharm
.Nd launch PyCharm Python Integrated Development Environment
.Sh SYNOPSIS
.Nm
.Op jvm-args
.Sh DESCRIPTION
.Nm
starts up the JetBrains PyCharm Community Edition Python Integrated
Development Environment.
.Sh SEE ALSO
The web site
.Lk https://www.jetbrains.com/pycharm/ .
