# $OpenBSD: Makefile,v 1.9 2013/10/11 23:48:42 naddy Exp $

COMMENT=	is a particular year a leap year

MODULES=	cpan
DISTNAME=	Date-Leapyear-1.72
REVISION=	0
CATEGORIES=	devel

MAINTAINER=	Sam Smith <S@msmith.net>

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
