MODGO_MODULES =	\
	github.com/google/go-cmp	 v0.6.0 \
	github.com/yuin/goldmark	 v1.4.13 \
	golang.org/x/crypto		 v0.33.0 \
	golang.org/x/mod		 v0.23.0 \
	golang.org/x/net		 v0.35.0 \
	golang.org/x/sync		 v0.11.0 \
	golang.org/x/sys		 v0.30.0 \
	golang.org/x/telemetry		 v0.0.0-20240521205824-bda55230c457 \
	golang.org/x/term		 v0.29.0 \
	golang.org/x/text		 v0.22.0

MODGO_MODFILES =	\
	golang.org/x/mod	 v0.17.0 \
	golang.org/x/sync	 v0.7.0 \
	golang.org/x/sys	 v0.20.0 \
	golang.org/x/tools	 v0.13.0

