MODGO_MODULES =	\
	github.com/google/go-cmp	 v0.6.0 \
	github.com/yuin/goldmark	 v1.4.13 \
	golang.org/x/crypto		 v0.55.0 \
	golang.org/x/mod		 v0.39.0 \
	golang.org/x/net		 v0.58.0 \
	golang.org/x/sync		 v0.22.0 \
	golang.org/x/sys		 v0.47.0 \
	golang.org/x/telemetry		 v0.0.0-20260811182544-a038080d80e5 \
	golang.org/x/term		 v0.45.0 \
	golang.org/x/text		 v0.41.0

MODGO_MODFILES =	\
	golang.org/x/tools	 v0.48.0

