MODGO_MODULES =	\
	github.com/google/go-cmp	 v0.6.0 \
	github.com/yuin/goldmark	 v1.4.13 \
	golang.org/x/crypto		 v0.43.0 \
	golang.org/x/mod		 v0.29.0 \
	golang.org/x/net		 v0.46.0 \
	golang.org/x/sync		 v0.17.0 \
	golang.org/x/sys		 v0.37.0 \
	golang.org/x/telemetry		 v0.0.0-20251008203120-078029d740a8 \
	golang.org/x/term		 v0.36.0 \
	golang.org/x/text		 v0.30.0

MODGO_MODFILES =	\
	golang.org/x/tools	 v0.37.0

