# $OpenBSD: Makefile,v 1.17 2019/10/20 08:03:04 ajacoutot Exp $

COMMENT =	precision raster image convolution engine

REVISION =	6
DISTNAME =	PRICE-1.3.0
CATEGORIES =	graphics

HOMEPAGE =	http://price.sourceforge.net/
MASTER_SITES =	${MASTER_SITE_SOURCEFORGE:=price/}

MODULES =	x11/gnustep
WANTLIB += ${COMPILER_LIBCXX}

.include <bsd.port.mk>
