COMMENT =		reusable constraint types to use with PEP 593 annotations

MODPY_DISTV =	0.7.0
DISTNAME =		annotated_types-${MODPY_DISTV}
PKGNAME =		py-${DISTNAME}
CATEGORIES =		devel
HOMEPAGE =		https://github.com/annotated-types/annotated-types
REVISION =		0

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python
MODPY_PI =		Yes
MODPY_PYBUILD =		hatchling

.include <bsd.port.mk>
