# $OpenBSD: Makefile,v 1.2 2004/01/17 15:58:07 naddy Exp $

NOT_FOR_ARCHS=	${NO_SHARED_ARCHS}

COMMENT=	"handles various Japanese charsets"

DISTNAME=	Jcode-0.83
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	converters japanese perl5

HOMEPAGE=	http://openlab.ring.gr.jp/Jcode/

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=   ${MASTER_SITE_PERL_CPAN:=../by-authors/id/D/DA/DANKOGAI/}

CONFIGURE_STYLE= perl

.include <bsd.port.mk>
