# $OpenBSD: Makefile,v 1.12 2018/04/24 18:06:30 sthen Exp $

COMMENT=	Tor Browser meta package

MAINTAINER=	Sean Levy <attila@stalphonsos.com>

PKGNAME=	tor-browser-7.5.3

RUN_DEPENDS=	www/tor-browser/browser>=7.5.3 \
		www/tor-browser/torbutton>=1.9.8.6 \
		www/tor-browser/tor-launcher>=0.2.14.4 \
		www/tor-browser/noscript>=5.1.8.4 \
		www/tor-browser/https-everywhere>=2018.3.13

.include <bsd.port.mk>
