.TH firefox 1 "August 07, 2012" firefox "Unix User's Manual"
.SH NAME
firefox \- redesign of Mozilla's browser component.

.SH SYNOPSIS
.B firefox
[\fIOPTIONS\fR] [\fIURL\fR]

.SH DESCRIPTION
\fBFirefox\fR is an open-source web browser, designed for standards compliance,
performance and portability.

.SH OPTIONS
A summary of the options supported by \fBfirefox\fR is included below.

.SS "X11 options"
.TP
.BI \-\-display= DISPLAY
X display to use
.TP
.B \--sync
Make X calls synchronous
.TP
.B \-\-g-fatal-warnings
Make all warnings fatal

.SS "Firefox options"
.TP
.B \-h, \-help
Show summary of options.
.TP
.B \-v, \-version
Print \fBfirefox\fR version.
.TP
\fB\-P\fR \fIprofile\fR
Start with \fIprofile\fR.
.TP
.B \-migration
Start with the migration wizard.
.TP
.B \-ProfileManager
Start with profile manager.
.TP
.B \-no-remote
Do not accept or send remote commands; implies -new-instance.
.TP
.B \-new-instance
Open new instance, not a new window in running instance.
.TP
\fB\-UILocale\fR \fIlocale\fR
Start with \fIlocale\fR resources as UI Locale.
.TP
.B \-safe-mode
Disables extensions and themes for the session.
.TP
.B \-jsconsole
Start with Javascript Console
.TP
.B \-browser
Open a browser window.
.TP
\fB\-new-window\fR \fIurl\fR
Open \fIurl\fR in a new window.
.TP
\fB\-new-tab\fR \fIurl\fR
Open \fIurl\fR in a new tab.
.TP
.B \-preferences
Open Preferences dialog.
.TP
\fB\-search\fR \fIterm\fR
Search \fIterm\fR with your default search engine.
.TP
.B \-private
Enable private browsing mode.
.TP
.B \-private-toggle
Toggle private browsing mode.
.TP
.B \-setDefaultBrowser
Set \fBfirefox\fR as the default browser.

.SH FILES
\fI${TRUEPREFIX}/bin/firefox\fR - \fBfirefox\fR executable

.SH VERSION
${MOZILLA_VERSION}

.SH BUGS
To report a bug, please visit \fIhttps://bugzilla.mozilla.org/\fR

.SH "SEE ALSO"
\fB${TRUEPREFIX}/share/doc/pkg-readme/firefox\fR

.SH AUTHORS
.TP
.B The Mozilla Organization
.I http://www.mozilla.org/about/
