# $OpenBSD: Makefile,v 1.22 2013/03/27 16:11:30 sthen Exp $

SHARED_ONLY=	Yes

COMMENT=	module for creating generic methods

MODULES=	cpan
DISTNAME=	Class-MethodMaker-2.18
CATEGORIES=	devel

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

PERMIT_PACKAGE_CDROM=   Yes

WANTLIB += c

.include <bsd.port.mk>
