# $OpenBSD: Makefile,v 1.20 2016/03/20 19:56:57 naddy Exp $

COMMENT =		Perl defines relating to AF_INET6 sockets

DISTNAME =		Socket6-0.26

CATEGORIES =		net devel

MAINTAINER =		Alexander Bluhm <bluhm@openbsd.org>

# 3-clause BSD
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB +=		c perl

MODULES =		cpan

.include <bsd.port.mk>
