# $OpenBSD: Makefile,v 1.4 2010/09/03 14:39:07 sthen Exp $

COMMENT=	curses DX cluster watcher

DISTNAME=	colrdx-1.02
REVISION=	0
CATEGORIES=    	comms hamradio

HOMEPAGE=	http://www.qsl.net/pg4i/linux/colrdx.html

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

WANTLIB=	c ncurses

MASTER_SITES=	http://www.qsl.net/pg4i/download/

.include <bsd.port.mk>
