COMMENT =		SPDX license list query tool

MODPY_DISTV =	0.3.3
DISTNAME =		spdx-lookup-${MODPY_DISTV}
PKGNAME =		py-spdx-lookup-${MODPY_DISTV}
REVISION =		3

CATEGORIES =		textproc

HOMEPAGE =		https://github.com/bbqsrc/spdx-lookup-python

# BSD-2-Clause
PERMIT_PACKAGE =	Yes

MODULES =		lang/python
MODPY_PYBUILD =		setuptools
MODPY_PI =		Yes

RUN_DEPENDS =		textproc/py-spdx

NO_TEST =		No tests written by upstream

.include <bsd.port.mk>
