COMMENT=	Python library for creating "editable wheels"

MODPY_DISTV=	0.6
DISTNAME=	editables-${MODPY_DISTV}
PKGNAME=	py-${DISTNAME}

CATEGORIES=	devel

HOMEPAGE=	https://github.com/pfmoore/editables

# MIT
PERMIT_PACKAGE=	Yes

MODULES=	lang/python
MODPY_PYBUILD=	flit_core
MODPY_PI=	Yes

TEST_DEPENDS=	devel/py-test-cov

.include <bsd.port.mk>
