# $OpenBSD: Makefile,v 1.16 2010/10/24 20:10:28 sebastia Exp $

     SUBDIR =
     SUBDIR += chipmunk
     SUBDIR += fritzing
     SUBDIR += geda-gaf
     SUBDIR += gerbv
     SUBDIR += gnucap
     SUBDIR += gtkwave
     SUBDIR += kicad
     SUBDIR += klogic
     SUBDIR += necpp
     SUBDIR += pcb
     SUBDIR += qcad
     SUBDIR += spice
     SUBDIR += xcircuit
     SUBDIR += xnecview
     SUBDIR += xtrkcad

.include <bsd.port.subdir.mk>
