htdocs_dir = '%%PREFIX%%/share/prewikka/htdocs'
database_dir = '%%PREFIX%%/share/prewikka/database'
locale_dir = '%%PREFIX%%/share/locale/'
conf_dir = '%%SYSCONFDIR%%/prewikka'
version = '%%VERSION%%'
libprelude_required_version = '0.9.24.1'
libpreludedb_required_version = '0.9.15.3'
