htdocs_dir = '%%PREFIX%%/share/prewikka/htdocs'
database_dir = '%%PREFIX%%/share/prewikka/database'
locale_dir = '%%PREFIX%%/share/locale/'
conf_dir = '%%SYSCONFDIR%%/prewikka'
version = '%%VERSION%%'
