# $OpenBSD: Makefile,v 1.8 2018/06/13 22:26:52 jeremy Exp $

COMMENT =	numerical N-dimensional Array class

DISTNAME =	narray-0.6.1.2
REVISION =	0
CATEGORIES =	devel

HOMEPAGE=	https://masa16.github.io/narray/

# GPLv2
PERMIT_PACKAGE_CDROM =	Yes

MODULES =	lang/ruby

CONFIGURE_STYLE =ruby gem ext

.include <bsd.port.mk>
