# $OpenBSD: Makefile,v 1.1.1.1 2003/02/21 13:44:19 avsm Exp $

COMMENT=	"calculate Fast Fourier Transforms in perl"

DISTNAME=	Math-FFT-0.25
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	math perl5

MAINTAINER=	Anil Madhavapeddy <avsm@openbsd.org>

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=   ${MASTER_SITE_PERL_CPAN:=Math/}

CONFIGURE_STYLE= perl

.include <bsd.port.mk>
