MODGO_MODULES = \
	github.com/!i!g!l!o!u-!e!u/go-wildcard	v1.0.3 \
	github.com/davecgh/go-spew		v1.1.1 \
	github.com/jedib0t/go-pretty/v6		v6.2.5 \
	github.com/kr/pretty			v0.2.0 \
	github.com/kr/pty			v1.1.1 \
	github.com/kr/text			v0.1.0 \
	github.com/lucasb-eyer/go-colorful	v1.2.0 \
	github.com/mattn/go-isatty		v0.0.14 \
	github.com/mattn/go-runewidth		v0.0.13 \
	github.com/muesli/mango			v0.1.0 \
	github.com/muesli/roff			v0.1.0 \
	github.com/muesli/termenv		v0.11.0 \
	github.com/pkg/profile			v1.6.0 \
	github.com/pmezard/go-difflib		v1.0.0 \
	github.com/rivo/uniseg			v0.2.0 \
	github.com/stretchr/objx		v0.1.0 \
	github.com/stretchr/testify		v1.7.0 \
	golang.org/x/sys			v0.0.0-20220114195835-da31bd327af9 \
	golang.org/x/term			v0.0.0-20210406210042-72f3dc4e9b72 \
	gopkg.in/check.v1			v1.0.0-20190902080502-41f04d3bba15 \
	gopkg.in/yaml.v3			v3.0.0-20210107192922-496545a6307b

MODGO_MODFILES =        \
	github.com/davecgh/go-spew	v1.1.0 \
	golang.org/x/sys		v0.0.0-20180816055513-1c9583448a9c \
	golang.org/x/sys		v0.0.0-20201119102817-f84b799fce68 \
	golang.org/x/sys		v0.0.0-20210630005230-0f9fa26af87c \
	gopkg.in/check.v1		v0.0.0-20161208181325-20d25e280405 \
	gopkg.in/yaml.v3		v3.0.0-20200313102051-9f266ea9e77c
