# $OpenBSD: Makefile,v 1.9 2012/08/30 14:09:21 sthen Exp $

COMMENT=	PHP support for setproctitle

DISTNAME=	proctitle-0.1.1
REVISION=	6

# PHP
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES=	lang/php/pecl
CONFIGURE_STYLE= gnu

.include <bsd.port.mk>
