# $OpenBSD: Makefile,v 1.29 2002/02/24 00:01:50 espie Exp $

COMMENT=	"superseded by splint"

DISTNAME=	lclint-2.5r
CATEGORIES=	devel
NEED_VERSION=	1.470

MAINTAINER=	Marc Espie <espie@openbsd.org>

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

BROKEN=		"superseded by splint"

.include <bsd.port.mk>
