# $OpenBSD: Makefile,v 1.16 2009/08/10 06:34:29 kili Exp $

COMMENT=	analog clock for GkrellM2

V=		0.3.3
DISTNAME=	gkrellaclock-${V}
PKGNAME=	${DISTNAME}p10
CATEGORIES=	misc

HOMEPAGE=	http://www.geocities.com/m_muthukumar/gkrellaclock.html

MASTER_SITES=	http://www.geocities.com/m_muthukumar/

WRKDIST=       	${WRKDIR}/gkrellAclock-${V}
ALL_TARGET=	gkrellaclock.so

PLUGIN=		${WRKSRC}/gkrellaclock.so

.include <bsd.port.mk>
