# $OpenBSD: Makefile,v 1.30 2004/09/15 00:06:59 pvalchev Exp $

COMMENT=	"tty-based e-mail client, development version"

VERSION=	1.5.6
MASTER_SITES=	${MASTER_SITES_MUTT:=devel/}

FLAVORS=	hcache

.include <bsd.port.mk>
