# $OpenBSD: Makefile,v 1.15 2020/05/27 11:38:18 bentley Exp $

COMMENT =		makefiles for building NetSurf

NETSURF_PROJECT =	buildsystem
NETSURF_VERSION =	1.9
DISTNAME =		${NETSURF_PROJECT}-${NETSURF_VERSION}
PKGNAME =		netsurf-${NETSURF_PROJECT}-${NETSURF_VERSION}

DEBUG_PACKAGES =

HOMEPAGE =		https://www.netsurf-browser.org/

NO_TEST =		Yes
NO_BUILD =		Yes

.include <bsd.port.mk>
