# $OpenBSD: Makefile,v 1.5 2007/09/14 22:51:21 eric Exp $
# $FreeBSD: Makefile,v 1.4 1997/06/03 09:14:50 asami Exp $

     SUBDIR += geos
     SUBDIR += globe
     SUBDIR += gpsbabel
     SUBDIR += jeoip
     SUBDIR += openbsd-developers

.include <bsd.port.subdir.mk>
