# $OpenBSD: Makefile,v 1.11 2016/03/20 19:56:52 naddy Exp $

COMMENT=	recursive FTP client module

MODULES=	cpan
PKG_ARCH=	*
DISTNAME =	Net-FTP-Recursive-2.04
CATEGORIES=	net

MAINTAINER=	Sam Smith <s@msmith.net>

# Perl
PERMIT_PACKAGE_CDROM=	Yes

WRKDIST =	${WRKDIR}/Net-FTP-Recursive

MODCPAN_EXAMPLES=	Yes
MODCPAN_EXAMPLES_DIST=	samples

.include <bsd.port.mk>
