# OpenBSD makefile for:	xprompt
# Version required:	1.4
# Date created:		11 January 1998
# Whom:			Don Schmidt
#
# $OpenBSD: Makefile,v 1.5 2000/03/17 02:34:45 kevlo Exp $
#

DISTNAME=	xprompt-1.4
CATEGORIES=	x11
MASTER_SITES=   ftp://ftp.nsg.bc.ca/pub/nsg/src/xprompt/

MAINTAINER=	ports@OpenBSD.ORG

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

FAKE=		Yes
USE_IMAKE=	Yes

.include <bsd.port.mk>
