COMMENT =		ssh configuration security auditing tool

MODPY_DISTV =	3.3.0

DISTNAME =		ssh_audit-${MODPY_DISTV}
PKGNAME =		ssh-audit-${MODPY_DISTV}
REVISION =		0

CATEGORIES =		security

HOMEPAGE =		https://github.com/jtesta/ssh-audit/

MAINTAINER =		Pavel Korovin <pvk@openbsd.org>

# Apache
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_PYBUILD =		setuptools

NO_TEST =		Yes

.include <bsd.port.mk>
