# $OpenBSD: Makefile,v 1.10 2000/10/22 14:03:15 espie Exp $

DISTNAME=	xbl-1.0j
CATEGORIES=	games
MASTER_SITES=	ftp://ftp710.univ-lyon1.fr/pub/xbl/
EXTRACT_SUFX=	.tar.Z

MAINTAINER=	Angelos D. Keromytis <angelos@openbsd.org>

LICENSE_TYPE=		GPL
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

USE_X11=	Yes
FAKE=		Yes
GNU_CONFIGURE=	Yes

.include <bsd.port.mk>
