JICOFO_CONF=${SYSCONFDIR}/jicofo/jicofo.conf
JICOFO_LOG_CONFIG=${SYSCONFDIR}/jicofo/logging.properties
JICOFO_TRUSTSTORE=${SYSCONFDIR}/ssl/jitsi.store
JICOFO_TRUSTSTORE_PASSWORD='${JAVA_TS_PASS}'
JICOFO_MAXMEM=3G
JICOFO_DHKEYSIZE=2048
