COMMENT =		ORM (Object Relational Manager) for Python

MODPY_EGG_VERSION =	3.10.1
DISTNAME =		SQLObject-${MODPY_EGG_VERSION}
PKGNAME =		py-sqlobject-${MODPY_EGG_VERSION}

CATEGORIES =		databases

HOMEPAGE =		http://www.sqlobject.org/

# LGPL
PERMIT_PACKAGE =	Yes

FLAVORS =		python3
FLAVOR =		python3

MODPY_PI =		Yes
MODPY_PYBUILD =		setuptools

MODULES =		lang/python
RUN_DEPENDS =		www/py-formencode${MODPY_FLAVOR} \
			devel/py-dispatcher${MODPY_FLAVOR}

.include <bsd.port.mk>
