# ncurses library finder
if(NCURSES_INCLUDE_DIR AND NCURSES_LIBRARY)
	set(NCURSES_FOUND TRUE)
else(NCURSES_INCLUDE_DIR AND NCURSES_LIBRARY)
	FIND_PATH(NCURSES_INCLUDE_DIR ncurses.h)

	FIND_LIBRARY(NCURSES_LIBRARY NAMES ncurses)
        include(FindPackageHandleStandardArgs)
        FIND_PACKAGE_HANDLE_STANDARD_ARGS(ncurses DEFAULT_MSG NCURSES_INCLUDE_DIR NCURSES_LIBRARY )

	MARK_AS_ADVANCED(NCURSES_INCLUDE_DIR NCURSES_LIBRARY)
endif(NCURSES_INCLUDE_DIR AND NCURSES_LIBRARY)
