# $OpenBSD: Makefile,v 1.14 2000/10/22 14:03:05 espie Exp $

DISTNAME=	automake-1.4
CATEGORIES=	devel
NEED_VERSION=	1.301
MASTER_SITES=	${MASTER_SITE_GNU}
MASTER_SITE_SUBDIR= automake

HOMEPAGE=	http://www.gnu.org/software/automake/

MAINTAINER=	Jason Ish <jasoni@openbsd.org>

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

CONFIGURE_STYLE= gnu

.include <bsd.port.mk>
