# $OpenBSD: Makefile,v 1.25 2018/07/15 08:36:39 espie Exp $

COMMENT=	changing xterm attributes

DISTNAME=	xtattr-1.0
REVISION=	0
CATEGORIES=	x11

PERMIT_PACKAGE_CDROM=	no license
PERMIT_PACKAGE_FTP=	no license
PERMIT_DISTFILES_FTP=	no license

MASTER_SITES =	${MASTER_SITE_FREEBSD}
WANTLIB=		c 

CONFIGURE_STYLE=	imake

NO_TEST=	Yes

.include <bsd.port.mk>
