# $OpenBSD: Makefile,v 1.4 2016/03/20 19:57:02 naddy Exp $

COMMENT=	generate pronounceable passwords

MODULES=	cpan
PKG_ARCH=	*
DISTNAME=	Text-Password-Pronounceable-0.30

CATEGORIES=	security

# Perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
