# $OpenBSD: Makefile,v 1.4 2010/07/30 06:59:00 ajacoutot Exp $

COMMENT=	Ruby implementation of the D-Bus protocol

DISTNAME=	ruby-dbus-0.2.1
REVISION=	0

CATEGORIES=	x11 devel

# gpl
PERMIT_PACKAGE_CDROM=	yes
PERMIT_PACKAGE_FTP=	yes
PERMIT_DISTFILES_CDROM=	yes
PERMIT_DISTFILES_FTP=	yes

MASTER_SITES=	https://trac.luon.net/data/ruby-dbus/releases/

MODULES=	lang/ruby

CONFIGURE_STYLE=ruby setup

PKG_ARCH=	*

.include <bsd.port.mk>
