# $OpenBSD: Makefile,v 1.2 2004/01/09 01:27:43 jolan Exp $

COMMENT=	"window decoration themes for xfwm4"
DISTNAME=	xfwm4-themes-${V}

HOMEPAGE=	http://www.xfce.org/en/xfwm4_themes.html

RUN_DEPENDS=	:xfwm4-*:x11/xfce4/desktop/xfwm4

.include <bsd.port.mk>
