COMMENT =	Perl unit testing framework

DISTNAME =	Test-Unit-0.25
REVISION =	3

CATEGORIES =	devel

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Class-Inner \
			devel/p5-Devel-Symdump \
			devel/p5-Error \

PKG_ARCH =		*

.include <bsd.port.mk>
