#   $OpenBSD: Makefile,v 1.10 2019/07/12 20:47:35 sthen Exp $

COMMENT=	implements a complete, RFC compliant SMTP server

DISTNAME=	SMTP-Server-1.1
REVISION=	1
CATEGORIES=	mail
MASTER_SITES=	${MASTER_SITE_PERL_CPAN:=Net/} \
		http://www.macgyver.org/software/perl/

HOMEPAGE=	http://www.macgyver.org/software/perl/

PERMIT_PACKAGE=	Yes

MODULES=	cpan
PKG_ARCH=	*

.include <bsd.port.mk>
