# $OpenBSD: Makefile,v 1.10 2007/04/12 18:59:36 jasper Exp $

COMMENT=		"traceroute(1) functionality in perl"

MODULES=		cpan
DISTNAME=		Net-Traceroute-1.09
PKGNAME=		p5-${DISTNAME}p0
CATEGORIES=		net

HOMEPAGE=		http://www.linnaean.org/~hag/perl/traceroute/traceroute.html

MAINTAINER=		Jasper Lievisse Adriaanse <jasper@openbsd.org>

# License: MIT
PERMIT_PACKAGE_CDROM=	Yes 
PERMIT_PACKAGE_FTP=	Yes 
PERMIT_DISTFILES_CDROM= Yes 
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
