# $OpenBSD: Makefile,v 1.3 2006/11/14 09:55:38 msf Exp $

COMMENT= 	"module for inspecting Perl's symbol table"

MODULES=	cpan

DISTNAME=	Devel-Symdump-2.0604
CATEGORIES=	devel perl5

MAINTAINER=	Mathieu Sauve-Frankel <msf@openbsd.org>

# Artistic
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MAKE_ENV=	TEST_POD=Yes

.include <bsd.port.mk>
