#!/bin/sh
# $OpenBSD: DEINSTALL,v 1.3 2004/04/15 07:34:11 xsa Exp $
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
SYSCONFDIR=${SYSCONFDIR:-/etc}
CONFIG_FILE=${SYSCONFDIR}/ffproxy.conf
FFPROXYDIR=/var/ffproxy
FFPROXYUSER=_ffproxy
FFPROXYGROUP=_ffproxy

if [ ${PKG_DELETE_EXTRA} != Yes -a -f $CONFIG_FILE ]; then
	echo
	echo "+---------------"
	echo "| To completely deinstall the $1 package you need to perform"
	echo "| these steps as root:"
	echo "|"
	if userinfo -e $FFPROXYUSER; then
	echo "|	userdel $FFPROXYUSER"
	fi
	if groupinfo -e $FFPROXYGROUP; then
	echo "|	groupdel $FFPROXYGROUP"
	fi
	echo "|	rm -f $CONFIG_FILE"
	if [ -d $FFPROXYDIR ]; then
	echo "|	rm -rf $FFPROXYDIR"
	fi
	echo "|"
	echo "| Do not do this if you plan on re-installing $1"
	echo "| at some future time."
	echo "+---------------"
	echo
fi

exit 0
