# Disable device monitors relying on facilities not available on OpenBSD:
# udev-based ALSA/V4L2 enumeration, BlueZ and logind.
wireplumber.profiles = {
  main = {
    monitor.alsa = disabled
    monitor.alsa-midi = disabled
    monitor.bluez = disabled
    monitor.bluez-midi = disabled
    monitor.bluez.seat-monitoring = disabled
    monitor.v4l2 = disabled
    support.logind = disabled
  }
}
