# $OpenBSD: Makefile,v 1.1.1.1 2010/07/28 20:06:15 sthen Exp $

COMMENT=	helper class for PHP WebDAV server implementations

V=		1.0.0RC4
DISTNAME=	HTTP_WebDAV_Server-$V
PKGNAME=	pear-HTTP-WebDAV-Server-${V:L}
CATEGORIES=	www

MODULES=	www/pear

# PHP License
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
