# $OpenBSD: Makefile,v 1.4 2020/07/03 21:45:22 sthen Exp $

COMMENT =	generate pleasant color schemes in Perl

DISTNAME =	Color-Scheme-1.07
REVISION =	1

CATEGORIES =	graphics

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

PKG_ARCH =		*

.include <bsd.port.mk>
