COMMENT =	generate pleasant color schemes in Perl

DISTNAME =	Color-Scheme-1.08
REVISION =	0

CATEGORIES =	graphics

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

PKG_ARCH =		*

.include <bsd.port.mk>
