# $OpenBSD: Makefile,v 1.9 2015/01/21 06:13:47 bentley Exp $

COMMENT=	impromptu dumping of data structures for debugging purposes

MODULES=	cpan
DISTNAME=	BFD-0.31
REVISION=	2
CATEGORIES=	devel

PERMIT_PACKAGE_CDROM=	Yes

CPAN_AUTHOR=	RBS

.include <bsd.port.mk>
