# $OpenBSD: Makefile,v 1.60 2016/10/28 13:47:52 ajacoutot Exp $

PKG_ARCH=		*

COMMENT=		developer documentation for GNOME

GNOME_PROJECT=		gnome-devel-docs
GNOME_VERSION=		3.22.1

# GPLv2
PERMIT_PACKAGE_CDROM=	Yes

MODULES=		x11/gnome

MODGNOME_TOOLS=		yelp

.include <bsd.port.mk>
