# $OpenBSD: Makefile,v 1.13 2013/03/11 01:30:27 espie Exp $

COMMENT= 		currency conversion

DISTNAME=		Finance-Currency-Convert-XE-0.22
CATEGORIES=		converters
MODULES=		cpan

# Artistic 2.0
PERMIT_PACKAGE_CDROM=	Yes

CPAN_AUTHOR=		RMCKAY

RUN_DEPENDS=		www/p5-HTML-Parser \
			www/p5-WWW-Mechanize

.include <bsd.port.mk>
