# $OpenBSD: Makefile,v 1.8 2010/12/08 22:13:25 jeremy Exp $

COMMENT =	filter controller parameters

DISTNAME =	merb-param-protection-${VERSION}

RUN_DEPENDS =	www/ruby-merb/core,${MODRUBY_FLAVOR}${MERB_REL_VER_SPEC}

.include <bsd.port.mk>
