.Dd December 8, 2001
.Dt WMTUNE 1
.Sh NAME
.Nm wmtune
.Nd premier dockable radio tuner
.Sh SYNOPSIS
.Nm wmtune
.Op Fl n
.Op Fl f Ar filename
.Op Fl t Ar hh:mm
.Op Fl p Ar ##
.Op Fl h
.Sh DESCRIPTION
The
.Nm
is a WindowMaker dock.app that controls AIMS Lab RadioTrack, Zoltrix,
Aztech/PackardBell FM radio tuner cards and cards supported by OpenBSD (native
mode).
.Pp
The
.Ql +
and
.Ql \-
buttons are for FINE tuning.
.Pp
The 2 buttons to the right of the FINE tuning buttons are the SCAN buttons.
.Pp
The 2 SCAN buttons also double as VOLUME UP/DOWN when using the RIGHT mouse
button.
.Pp
In the bottom left there is a small two digit box in which the currently
selected preset will be shown.
The
.Ql <
and
.Ql >
arrow buttons to the left of the box allow to switch between
presets easily and quickly.
.Pp
To the right of the above described things there is yet another button with
a miniature ON/OFF logo.
This is used to turn your radio card on/off.
.Pp
The button with the inscribed letter
.Ql A
allows you to control the internal alarm clock/delay timer.
Upon pressing the
.Ql A
button you will be allowed to set the timer/delay to a time you wish the radio
to turn on/off (depending on the current state of the radio) automatically.
.Pp
After pressing the
.Ql A
button the first time you may set the now displayed clock type panel to
the desired setting using the SCAN buttons to set your timer in the 24 hour
format (be aware in this state other buttons cease to work).
You must press the
.Ql A
button again at which point the indicator light will turn on and the alarm
will be set.
Lastly, pressing the
.Ql A
button once more, will disengance the timer.
.Sh OPTIONS
.Bl -tag -width filename
.It Fl f Ar filename
Use
.Ar filename
as a radio device file (only for wmtune which uses native OpenBSD drivers).
.It Fl n
Turn radio on initially on startup.
.It Fl t Ar hh:mm
Set timer on startup, military time.
.It Fl p Ar ##
Set startup preset # listed in wmtunerc file.
.It Fl h
Display help screen.
.Sh EXAMPLES
.Dl wmtune -n -p 5
.Dl wmtune -p 2 -t 14:35
.Dl wmtune -n -t 00:00
.Sh ENVIRONMENT
The following environment variable affects the execution of
.Nm wmtune
in the OpenBSD native mode:
.Bl -tag -width RADIODEVICE
.It Ev RADIODEVICE
The radio tuner device to use.
.El
.Sh FILES
.Bl -tag -width /dev/wmtunerc
.It /etc/wmtunerc
global configuration file
.It ~/.wmtunerc
user configuration file
.It /dev/radio
default radio device in the native mode
.El
.Sh SEE ALSO
.Xr radioctl 1 ,
.Xr radio 4
.Sh AUTHORS
.Nm
written by
.An soren Aq soren@leiden.org , 
the manpage written by
.An Vladimir Popov Aq pva48@mail.ru
