# $OpenBSD: Makefile,v 1.5 2007/09/15 20:59:40 merdely Exp $

SHARED_ONLY=	Yes

COMMENT=	comma-separated values manipulation routines

MODULES=	cpan
DISTNAME=	Text-CSV_XS-0.23
CATEGORIES=	textproc

MAINTAINER=	Chris Kuethe <ckuethe@ualberta.ca>

# GPL/Artistic
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

.include <bsd.port.mk>
