# $OpenBSD: Makefile,v 1.4 2014/10/11 19:54:47 jeremy Exp $

COMMENT=		lexical scanner generator for use with Racc

DISTNAME=		rexical-1.0.5
REVISION =		1
CATEGORIES=		textproc

HOMEPAGE=		https://github.com/tenderlove/rexical

# LGPLv2
PERMIT_PACKAGE_CDROM=	Yes

MODULES=		lang/ruby

CONFIGURE_STYLE=	ruby gem

.include <bsd.port.mk>
