# $OpenBSD: Makefile,v 1.24 2009/03/26 10:34:48 jasper Exp $

     SUBDIR += bruce
     SUBDIR += calcurse
     SUBDIR += devtodo
     SUBDIR += fet
     SUBDIR += gnucash
     SUBDIR += gnucash-docs
     SUBDIR += grisbi
     SUBDIR += gtg
     SUBDIR += gtimer
     SUBDIR += homebank
     SUBDIR += ledger
     SUBDIR += osmo
     SUBDIR += qhacc
     SUBDIR += siag
     SUBDIR += taskjuggler
     SUBDIR += tasks
     SUBDIR += tdl
     SUBDIR += thinkingrock
     SUBDIR += vym
     SUBDIR += workrave
     SUBDIR += wyrd
     SUBDIR += xinvest
     SUBDIR += xquote

.include <bsd.port.subdir.mk>
