# $OpenBSD: Makefile,v 1.10 2017/07/26 22:45:24 sthen Exp $

COMMENT =	language for typesetting graphs

DISTNAME =	grap-1.45
REVISION =	1
CATEGORIES =	textproc graphics

HOMEPAGE =	http://lunabase.org/~faber/Vault/software/grap/

MAINTAINER =	Hermann Gottschalk <magnum@pestilenz.org>

# BSD
PERMIT_PACKAGE_CDROM = Yes

MASTER_SITES =		${HOMEPAGE}
WANTLIB =		c m ${COMPILER_LIBCXX}
CONFIGURE_STYLE =	gnu

.include <bsd.port.mk>
