# $OpenBSD: Makefile,v 1.1.1.1 2011/06/23 10:11:44 ajacoutot Exp $

MODPY_EGG_VERSION =	2.0.0
TRYTOND_MODULE =	analytic_invoice

RUN_DEPENDS =		productivity/tryton/account_invoice \
			productivity/tryton/analytic_account

.include <bsd.port.mk>
