# $OpenBSD: Makefile,v 1.8 2014/11/22 09:26:37 benoit Exp $

COMMENT=	preparation of internationalized strings

DISTNAME =	Unicode-Stringprep-1.105
CATEGORIES=	converters

# perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES=		cpan

CONFIGURE_STYLE=	modbuild

TEST_DEPENDS=	devel/p5-Test-NoWarnings

.include <bsd.port.mk>
