# $OpenBSD: Makefile,v 1.5 2005/11/22 07:45:21 kevlo Exp $

COMMENT=	"run a subprocess in batch mode"

DISTNAME=	IPC-Run3-0.033
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	devel perl5

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=	${MASTER_SITE_PERL_CPAN:=IPC/}

CONFIGURE_STYLE= perl

.include <bsd.port.mk>
