# $OpenBSD: Makefile,v 1.2 2010/10/18 17:47:58 espie Exp $

COMMENT=		easily dump variables with names

DISTNAME=		Data-Dumper-Simple-0.11

CATEGORIES=		devel

# perl
PERMIT_PACKAGE_FTP=	Yes
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes
PERMIT_DISTFILES_CDROM= Yes

MODULES=		cpan
USE_GROFF =	Yes

.include <bsd.port.mk>
