# $OpenBSD: Makefile,v 1.9 2013/03/11 10:50:29 espie Exp $

COMMENT =		port of Algorithm::Diff that uses the LCS algorithm

DISTNAME =		diff-lcs-1.1.2
REVISION =		5
CATEGORIES =		devel lang/ruby

# Perl Artistic
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/ruby

CONFIGURE_STYLE =	ruby gem

.include <bsd.port.mk>
