# $OpenBSD: Makefile,v 1.73 2014/03/15 13:12:56 edd Exp $

    SUBDIR =
    SUBDIR += BasiliskII
    SUBDIR += bochs
    SUBDIR += bochs,debug
    SUBDIR += coldfire
    SUBDIR += desmume
    SUBDIR += dgen-sdl
    SUBDIR += dgen-sdl,debugger
    SUBDIR += dosbox
    SUBDIR += dynagen
    SUBDIR += dynamips
    SUBDIR += fceux
    SUBDIR += fedora
    SUBDIR += frodo
    SUBDIR += fuse
    SUBDIR += fuse-utils
    SUBDIR += fs-uae
    SUBDIR += fs-uae-launcher
    SUBDIR += gambatte
    SUBDIR += gns3
    SUBDIR += gnusim8085
    SUBDIR += gxemul
    SUBDIR += mednafen
    SUBDIR += mupen64plus
    SUBDIR += nestopia
    SUBDIR += openmsx
    SUBDIR += qemu
    SUBDIR += pcsxr
    SUBDIR += redhat
    SUBDIR += sdlmame
    SUBDIR += sdlmess
    SUBDIR += simh
    SUBDIR += snes9x
    SUBDIR += spectemu
    SUBDIR += spim
    SUBDIR += stella
    SUBDIR += uae
    SUBDIR += vbam
    SUBDIR += x48
    SUBDIR += xnp2
    SUBDIR += xcopilot
    SUBDIR += xhomer
    SUBDIR += yabause
    SUBDIR += zsnes

.include <bsd.port.subdir.mk>
