# $OpenBSD: Makefile,v 1.29 2004/10/07 03:07:31 jsg Exp $

    SUBDIR += BasiliskII
    SUBDIR += bochs
    SUBDIR += bochs,debug
    SUBDIR += dosbox
    SUBDIR += freebsd_lib
    SUBDIR += frodo
    SUBDIR += fuse
    SUBDIR += fuse-utils
    SUBDIR += ines
    SUBDIR += mastergear
    SUBDIR += mips64emul
    SUBDIR += redhat
    SUBDIR += simh
    SUBDIR += snes9x
    SUBDIR += spectemu
    SUBDIR += spim
    SUBDIR += uae
    SUBDIR += vgb
    SUBDIR += vmware/3
    SUBDIR += wine
    SUBDIR += x48
    SUBDIR += xcopilot
    SUBDIR += xmame
    SUBDIR += zsnes

.include <bsd.port.subdir.mk>
