# $OpenBSD: Makefile,v 1.11 2016/03/20 19:57:24 naddy Exp $

COMMENT=	splash screen widget

DISTNAME=	Tk-Splash-0.16
CATEGORIES=	x11 devel

# GPL
PERMIT_PACKAGE_CDROM=	Yes

RUN_DEPENDS=	x11/p5-Tk

MODULES=	cpan
PKG_ARCH=	*

TEST_IS_INTERACTIVE= x11

.include <bsd.port.mk>
