# $OpenBSD: Makefile,v 1.2 2019/07/12 20:50:53 sthen Exp $

COMMENT=	change long page list to be shorter and well navigate

MODULES=	cpan
PKG_ARCH=	*
DISTNAME=	Data-Page-Pageset-1.02
CATEGORIES=	www

# perl
PERMIT_PACKAGE=	Yes

BUILD_DEPENDS=	databases/p5-Data-Page

.include <bsd.port.mk>
