# $OpenBSD: Makefile,v 1.3 2010/10/18 17:48:10 espie Exp $

COMMENT=                create accessor methods in caller's package

DISTNAME=               accessors-1.01
CATEGORIES=             devel

# Artistic/GPL
PERMIT_PACKAGE_FTP=     Yes
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_DISTFILES_FTP=   Yes
PERMIT_DISTFILES_CDROM= Yes

CONFIGURE_STYLE=        modbuild

MODULES=                cpan
USE_GROFF =	Yes
CPAN_AUTHOR=            SPURKIS

PKG_ARCH=		*

.include <bsd.port.mk>
