# $OpenBSD: Makefile,v 1.13 2014/03/23 14:52:15 jasper Exp $

COMMENT=	lists of Perl keywords for use in backend modules

MODULES=	cpan

DISTNAME=	B-Keywords-1.13
CATEGORIES=	devel

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
