MODGO_MODULES =	\
	c2sp.org/!c!c!t!v/age		 v0.0.0-20240306222714-3ec4d716e805 \
	filippo.io/edwards25519		 v1.1.0 \
	github.com/google/go-cmp	 v0.6.0 \
	github.com/rogpeppe/go-internal	 v1.12.0 \
	github.com/yuin/goldmark	 v1.4.13 \
	golang.org/x/crypto		 v0.24.0 \
	golang.org/x/mod		 v0.18.0 \
	golang.org/x/net		 v0.26.0 \
	golang.org/x/sync		 v0.7.0 \
	golang.org/x/sys		 v0.21.0 \
	golang.org/x/telemetry		 v0.0.0-20240521205824-bda55230c457 \
	golang.org/x/term		 v0.21.0 \
	golang.org/x/text		 v0.16.0 \
	golang.org/x/tools		 v0.22.0

MODGO_MODFILES =	\
	golang.org/x/crypto	 v0.24.0 \
	golang.org/x/mod	 v0.18.0 \
	golang.org/x/net	 v0.26.0 \
	golang.org/x/sys	 v0.21.0 \
	golang.org/x/tools	 v0.22.0

