# $OpenBSD: Makefile,v 1.9 2020/07/03 21:44:46 sthen Exp $

COMMENT=        hexadecimal dumper

MODULES=	cpan
PKG_ARCH=	*
DISTNAME=	Data-HexDump-0.02
REVISION=	2
CATEGORIES=     devel

MAINTAINER=	Abel Abraham Camarillo Ojeda <acamari@verlet.org>

# perl
PERMIT_PACKAGE=	Yes

.include <bsd.port.mk>
