MODGO_MODULES =	\
	github.com/creack/pty		 v1.1.9 \
	github.com/davecgh/go-spew	 v1.1.1 \
	github.com/kr/pretty		 v0.3.1 \
	github.com/kr/text		 v0.2.0 \
	github.com/mjwhitta/cli		 v1.14.2 \
	github.com/mjwhitta/errors	 v1.0.8 \
	github.com/mjwhitta/hilighter	 v1.15.2 \
	github.com/mjwhitta/log		 v1.8.10 \
	github.com/mjwhitta/pathname	 v1.3.2 \
	github.com/mjwhitta/safety	 v1.12.2 \
	github.com/mjwhitta/sysinfo	 v1.7.8 \
	github.com/mjwhitta/where	 v1.3.14 \
	github.com/pkg/diff		 v0.0.0-20210226163009-20ebb0f2a09e \
	github.com/pmezard/go-difflib	 v1.0.0 \
	github.com/rogpeppe/go-internal	 v1.9.0 \
	github.com/stretchr/objx	 v0.5.2 \
	github.com/stretchr/testify	 v1.11.1 \
	golang.org/x/sys		 v0.46.0 \
	gopkg.in/check.v1		 v1.0.0-20201130134442-10cb98267c6c \
	gopkg.in/yaml.v3		 v3.0.1

MODGO_MODFILES =	\
	gopkg.in/check.v1	 v0.0.0-20161208181325-20d25e280405

