#!/bin/sh
#
# $OpenBSD: varnishreload,v 1.2 2020/01/18 11:34:34 kn Exp $
#
# Reload active VCL.
set -Cefu

if getopts '' _ || [ $# -ge 2 ]; then
	printf 'usage:\t%s [file]\n' "${0##*/}" 1>&2
	exit 1
fi

FILE=${1:-${SYSCONFDIR}/varnish/default.vcl}
NAME=${FILE##*/}
NAME=${NAME%%.*}_$(date +%Y%m%d%H%M%S)

${TRUEPREFIX}/bin/varnishadm -- vcl.load "$NAME" "$FILE"
${TRUEPREFIX}/bin/varnishadm -- vcl.use "$NAME"
