MODCARGO_CRATES +=	bit_field	0.10.2	# Apache-2.0/MIT
MODCARGO_CRATES +=	proc-macro2	1.0.76	# MIT OR Apache-2.0
MODCARGO_CRATES +=	quote	1.0.35	# MIT OR Apache-2.0
MODCARGO_CRATES +=	syn	2.0.48	# MIT OR Apache-2.0
MODCARGO_CRATES +=	thiserror	1.0.64	# MIT OR Apache-2.0
MODCARGO_CRATES +=	thiserror-impl	1.0.64	# MIT OR Apache-2.0
MODCARGO_CRATES +=	unicode-ident	1.0.10	# (MIT OR Apache-2.0) AND Unicode-DFS-2016
