# $OpenBSD: Makefile,v 1.21 2020/12/03 07:54:51 benoit Exp $

COMMENT =	create and manipulate PAR distributions

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	PAR-Dist-0.51
CATEGORIES =	devel archivers

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# perl
PERMIT_PACKAGE=	Yes

MAKE_ENV =	PERL_TEST_POD=Yes TEST_POD=Yes

.include <bsd.port.mk>
