# $OpenBSD: Makefile,v 1.3 2018/01/01 12:34:10 bluhm Exp $

COMMENT =	check file names portability

DISTNAME =	Test-Portability-Files-0.09

CATEGORIES =	devel

MAINTAINER =		Alexander Bluhm <bluhm@openbsd.org>

# perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

PKG_ARCH =		*

.include <bsd.port.mk>
