@comment $OpenBSD: PFRAG.tcl,v 1.3 2001/02/22 19:28:14 danh Exp $
bin/pgaccess
bin/pgtclsh
bin/pgtksh
include/pgsql/libpgtcl.h
man/man1/pgaccess.1
man/man1/pgtclsh.1
man/man1/pgtksh.1
lib/pgsql/libpgtcl.a
lib/pgsql/pgaccess/images/icon_button.gif
lib/pgsql/pgaccess/images/icon_checkbutton.gif
lib/pgsql/pgaccess/images/icon_entry.gif
lib/pgsql/pgaccess/images/icon_frame.gif
lib/pgsql/pgaccess/images/icon_label.gif
lib/pgsql/pgaccess/images/icon_listbox.gif
lib/pgsql/pgaccess/images/icon_query.gif
lib/pgsql/pgaccess/images/icon_radiobutton.gif
lib/pgsql/pgaccess/images/icon_text.gif
lib/pgsql/pgaccess/lib/database.tcl
lib/pgsql/pgaccess/lib/forms.tcl
lib/pgsql/pgaccess/lib/functions.tcl
lib/pgsql/pgaccess/lib/help.tcl
lib/pgsql/pgaccess/lib/help/abort.hlp
lib/pgsql/pgaccess/lib/help/add_records.hlp
lib/pgsql/pgaccess/lib/help/alter_table.hlp
lib/pgsql/pgaccess/lib/help/alter_user.hlp
lib/pgsql/pgaccess/lib/help/author.hlp
lib/pgsql/pgaccess/lib/help/begin.hlp
lib/pgsql/pgaccess/lib/help/close.hlp
lib/pgsql/pgaccess/lib/help/cluster.hlp
lib/pgsql/pgaccess/lib/help/commit.hlp
lib/pgsql/pgaccess/lib/help/copy.hlp
lib/pgsql/pgaccess/lib/help/copyrights.hlp
lib/pgsql/pgaccess/lib/help/create_aggregate.hlp
lib/pgsql/pgaccess/lib/help/create_database.hlp
lib/pgsql/pgaccess/lib/help/create_function.hlp
lib/pgsql/pgaccess/lib/help/create_index.hlp
lib/pgsql/pgaccess/lib/help/create_language.hlp
lib/pgsql/pgaccess/lib/help/create_operator.hlp
lib/pgsql/pgaccess/lib/help/create_rule.hlp
lib/pgsql/pgaccess/lib/help/create_sequence.hlp
lib/pgsql/pgaccess/lib/help/create_table.hlp
lib/pgsql/pgaccess/lib/help/create_table_as.hlp
lib/pgsql/pgaccess/lib/help/create_trigger.hlp
lib/pgsql/pgaccess/lib/help/create_type.hlp
lib/pgsql/pgaccess/lib/help/create_user.hlp
lib/pgsql/pgaccess/lib/help/create_view.hlp
lib/pgsql/pgaccess/lib/help/data_types.hlp
lib/pgsql/pgaccess/lib/help/datefunc.hlp
lib/pgsql/pgaccess/lib/help/declare.hlp
lib/pgsql/pgaccess/lib/help/delete.hlp
lib/pgsql/pgaccess/lib/help/drop_aggregate.hlp
lib/pgsql/pgaccess/lib/help/drop_database.hlp
lib/pgsql/pgaccess/lib/help/drop_function.hlp
lib/pgsql/pgaccess/lib/help/drop_index.hlp
lib/pgsql/pgaccess/lib/help/drop_language.hlp
lib/pgsql/pgaccess/lib/help/drop_operator.hlp
lib/pgsql/pgaccess/lib/help/drop_rule.hlp
lib/pgsql/pgaccess/lib/help/drop_sequence.hlp
lib/pgsql/pgaccess/lib/help/drop_table.hlp
lib/pgsql/pgaccess/lib/help/drop_trigger.hlp
lib/pgsql/pgaccess/lib/help/drop_type.hlp
lib/pgsql/pgaccess/lib/help/drop_user.hlp
lib/pgsql/pgaccess/lib/help/drop_view.hlp
lib/pgsql/pgaccess/lib/help/explain.hlp
lib/pgsql/pgaccess/lib/help/fetch.hlp
lib/pgsql/pgaccess/lib/help/form_design.hlp
lib/pgsql/pgaccess/lib/help/forms.hlp
lib/pgsql/pgaccess/lib/help/functions.hlp
lib/pgsql/pgaccess/lib/help/geomfunc.hlp
lib/pgsql/pgaccess/lib/help/grant.hlp
lib/pgsql/pgaccess/lib/help/history.hlp
lib/pgsql/pgaccess/lib/help/index.hlp
lib/pgsql/pgaccess/lib/help/inheritance.hlp
lib/pgsql/pgaccess/lib/help/insert.hlp
lib/pgsql/pgaccess/lib/help/ipv4func.hlp
lib/pgsql/pgaccess/lib/help/isolation.hlp
lib/pgsql/pgaccess/lib/help/keywords.hlp
lib/pgsql/pgaccess/lib/help/listen.hlp
lib/pgsql/pgaccess/lib/help/load.hlp
lib/pgsql/pgaccess/lib/help/lock.hlp
lib/pgsql/pgaccess/lib/help/mathfunc.hlp
lib/pgsql/pgaccess/lib/help/move.hlp
lib/pgsql/pgaccess/lib/help/mvcc.hlp
lib/pgsql/pgaccess/lib/help/new_query.hlp
lib/pgsql/pgaccess/lib/help/new_table.hlp
lib/pgsql/pgaccess/lib/help/notify.hlp
lib/pgsql/pgaccess/lib/help/open_query.hlp
lib/pgsql/pgaccess/lib/help/open_table.hlp
lib/pgsql/pgaccess/lib/help/pgfunctions.hlp
lib/pgsql/pgaccess/lib/help/postgresql.hlp
lib/pgsql/pgaccess/lib/help/queries.hlp
lib/pgsql/pgaccess/lib/help/reports.hlp
lib/pgsql/pgaccess/lib/help/reset.hlp
lib/pgsql/pgaccess/lib/help/revoke.hlp
lib/pgsql/pgaccess/lib/help/rollback.hlp
lib/pgsql/pgaccess/lib/help/schema.hlp
lib/pgsql/pgaccess/lib/help/scripts.hlp
lib/pgsql/pgaccess/lib/help/select.hlp
lib/pgsql/pgaccess/lib/help/select_into.hlp
lib/pgsql/pgaccess/lib/help/sequences.hlp
lib/pgsql/pgaccess/lib/help/set.hlp
lib/pgsql/pgaccess/lib/help/show.hlp
lib/pgsql/pgaccess/lib/help/sql_guide.hlp
lib/pgsql/pgaccess/lib/help/sqlfunc.hlp
lib/pgsql/pgaccess/lib/help/stringfunc.hlp
lib/pgsql/pgaccess/lib/help/tables.hlp
lib/pgsql/pgaccess/lib/help/unlisten.hlp
lib/pgsql/pgaccess/lib/help/update.hlp
lib/pgsql/pgaccess/lib/help/users.hlp
lib/pgsql/pgaccess/lib/help/vacuum.hlp
lib/pgsql/pgaccess/lib/help/view_table_structure.hlp
lib/pgsql/pgaccess/lib/help/views.hlp
lib/pgsql/pgaccess/lib/help/visual_designer.hlp
lib/pgsql/pgaccess/lib/help/y2k.hlp
lib/pgsql/pgaccess/lib/languages/czech
lib/pgsql/pgaccess/lib/languages/deutsch
lib/pgsql/pgaccess/lib/languages/francais
lib/pgsql/pgaccess/lib/languages/italiano
lib/pgsql/pgaccess/lib/languages/magyar
lib/pgsql/pgaccess/lib/languages/portugues
lib/pgsql/pgaccess/lib/languages/romana
lib/pgsql/pgaccess/lib/languages/russian.koi8r
lib/pgsql/pgaccess/lib/languages/russian_win
lib/pgsql/pgaccess/lib/languages/spanish
lib/pgsql/pgaccess/lib/mainlib.tcl
lib/pgsql/pgaccess/lib/preferences.tcl
lib/pgsql/pgaccess/lib/queries.tcl
lib/pgsql/pgaccess/lib/reports.tcl
lib/pgsql/pgaccess/lib/schema.tcl
lib/pgsql/pgaccess/lib/scripts.tcl
lib/pgsql/pgaccess/lib/sequences.tcl
lib/pgsql/pgaccess/lib/tables.tcl
lib/pgsql/pgaccess/lib/users.tcl
lib/pgsql/pgaccess/lib/views.tcl
lib/pgsql/pgaccess/lib/visualqb.tcl
lib/pgsql/pgaccess/main.tcl
%%SHARED-tcl%%
@dirrm lib/pgsql/pgaccess/lib/languages
@dirrm lib/pgsql/pgaccess/lib/help
@dirrm lib/pgsql/pgaccess/lib
@dirrm lib/pgsql/pgaccess/images
@dirrm lib/pgsql/pgaccess
