MODGO_MODULES =	\
	github.com/gdamore/encoding		 v1.0.0 \
	github.com/gdamore/tcell/v2		 v2.5.3 \
	github.com/lucasb-eyer/go-colorful	 v1.2.0 \
	github.com/mattn/go-isatty		 v0.0.16 \
	github.com/mattn/go-runewidth		 v0.0.14 \
	github.com/mattn/go-shellwords		 v1.0.12 \
	github.com/rivo/uniseg			 v0.4.2 \
	github.com/saracen/walker		 v0.1.3 \
	golang.org/x/sync			 v0.0.0-20220601150217-0de741cfad7f \
	golang.org/x/sys			 v0.0.0-20220811171246-fbc7d0a398ab \
	golang.org/x/term			 v0.0.0-20210927222741-03fcf44c2211 \
	golang.org/x/text			 v0.3.7 \
	golang.org/x/tools			 v0.0.0-20180917221912-90fa682c2a6e

MODGO_MODFILES =	\
	github.com/mattn/go-runewidth	 v0.0.13 \
	github.com/rivo/uniseg		 v0.2.0 \
	golang.org/x/sys		 v0.0.0-20201119102817-f84b799fce68 \
	golang.org/x/sys		 v0.0.0-20210615035016-665e8c7367d1 \
	golang.org/x/sys		 v0.0.0-20220318055525-2edf467146b5 \
	golang.org/x/term		 v0.0.0-20201210144234-2321bbc49cbf \
	golang.org/x/text		 v0.3.0

