# $OpenBSD: Makefile,v 1.23 2019/07/12 20:43:54 sthen Exp $

COMMENT =	tie class for a simple ASCII database
DISTNAME =	AsciiDB-TagFile-1.06
REVISION =	1
CATEGORIES =	databases
MODULES =	cpan
PKG_ARCH =	*
FIX_EXTRACT_PERMISSIONS=Yes

MAINTAINER =	Marc Espie <espie@openbsd.org>

# Perl
PERMIT_PACKAGE =	Yes

.include <bsd.port.mk>
