MODGO_MODULES =	\
	github.com/google/go-cmp	 v0.5.8 \
	golang.org/x/exp		 v0.0.0-20230213192124-5e25df0256eb \
	golang.org/x/mod		 v0.6.0 \
	golang.org/x/net		 v0.7.0 \
	golang.org/x/sync		 v0.1.0 \
	golang.org/x/sys		 v0.5.0 \
	golang.org/x/term		 v0.5.0 \
	golang.org/x/text		 v0.7.0 \
	golang.org/x/tools		 v0.2.0
MODGO_MODFILES =	\
	golang.org/x/mod	 v0.6.0-dev.0.20220419223038-86c51ed26bb4 \
	golang.org/x/sys	 v0.0.0-20220722155257-8c9f86f7a55f \
	golang.org/x/sys	 v0.1.0 \
	golang.org/x/tools	 v0.1.12
