# $OpenBSD: Makefile,v 1.9 2007/09/15 18:44:37 steven Exp $

COMMENT=	manage sets of integers

MODULES=	cpan
DISTNAME=	Set-IntSpan-1.09
CATEGORIES=	math

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
