# $OpenBSD: Makefile,v 1.16 2020/08/16 20:35:19 sebastia Exp $

COMMENT =	extended TicTacToe game for GNUstep

DISTNAME =	Gomoku-1.2.9
REVISION =	13
CATEGORIES =	games

HOMEPAGE =	http://www.gnustep.it/nicola/Applications/Gomoku/
MASTER_SITES =	${HOMEPAGE}

MODULES =	x11/gnustep
WANTLIB += ${COMPILER_LIBCXX}

.include <bsd.port.mk>
