#!/bin/sh
# $OpenBSD: DEINSTALL,v 1.2 2004/04/14 09:27:52 xsa Exp $
#
# hlfl de-installation

set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PREFIX=${PKG_PREFIX:-/usr/local}
CONFIG_FILE=${SYSCONFDIR}/services.hlfl

if [ ${PKG_DELETE_EXTRA} != Yes -a -f "${CONFIG_FILE}" ]; then
    echo
    echo "+---------------"
    echo "| To completely deinstall the $1 package you need to perform"
    echo "| this step as root:"
    echo "|"
    echo "|           rm -f ${CONFIG_FILE}"
    echo "|"
    echo "| This is not necessary if you plan on re-installing $1"
    echo "| in the near future."
    echo "+---------------"
    echo
fi

exit 0
