# $OpenBSD: fortran.port.mk,v 1.16 2019/05/08 20:13:57 bcallah Exp $

MODFORTRAN_COMPILER ?= g77

.if empty(MODFORTRAN_COMPILER)
ERRORS += "Fatal: need to specify MODFORTRAN_COMPILER"
.endif

.if ${MODFORTRAN_COMPILER:L} == "g77"
MODFORTRAN_BUILD_DEPENDS += lang/g77 devel/libf2c
MODFORTRAN_LIB_DEPENDS += devel/libf2c
MODFORTRAN_WANTLIB += g2c
.elif ${MODFORTRAN_COMPILER:L} == "gfortran"
MODULES += gcc4
MODGCC4_ARCHS ?= *
MODGCC4_LANGS += fortran
MODFORTRAN_BUILD_DEPENDS += ${MODGCC4_FORTRANDEP}
MODFORTRAN_LIB_DEPENDS += ${MODGCC4_FORTRANLIBDEP}
MODFORTRAN_WANTLIB += ${MODGCC4_FORTRANWANTLIB}
.elif ${MODFORTRAN_COMPILER:L} == "flang"
MODFORTRAN_BUILD_DEPENDS += lang/flang/flang
MODFORTRAN_LIB_DEPENDS += lang/flang/flang
MODFORTRAN_WANTLIB += flang flangmain flangrti pgmath
.else
ERRORS += "Fatal: MODFORTRAN_COMPILER must be one of: g77 gfortran flang"
.endif
