# $OpenBSD: Makefile,v 1.4 1999/10/31 08:09:19 turan Exp $

BROKEN=			bad packing lists, man/man1/xdtm.1

DISTNAME=		xdtm-2.5.5
CATEGORIES=		x11
MASTER_SITES=		${MASTER_SITE_XCONTRIB}
MASTER_SITE_SUBDIR=	applications/xdtm

MAINTAINER=		angelos@openbsd.org

USE_IMAKE=		yes
WRKSRC=			${WRKDIR}/xdtm

.include <bsd.port.mk>
