# $OpenBSD: adj.mk,v 1.7 2019/11/11 22:54:15 edd Exp $
#
# This file is automatically generated. Do not edit.


BASH_ADJ_FILES += \
	texmf-dist/doc/cstex/cspsfonts-gen/mkf \
	texmf-dist/doc/cstex/cspsfonts-gen/mkfc \
	texmf-dist/doc/fonts/aecc/clean \
	texmf-dist/doc/fonts/aecc/go \
	texmf-dist/doc/fonts/aecc/install \
	texmf-dist/doc/fonts/aecc/makepl \
	texmf-dist/doc/fonts/drm/allcomp.sh \
	texmf-dist/doc/fonts/drm/allfonts.sh \
	texmf-dist/doc/fonts/drm/chartscript.sh \
	texmf-dist/doc/fonts/hfbright/generate.sh \
	texmf-dist/doc/fonts/oldstandard/gendocs.sh \
	texmf-dist/doc/generic/e-french/bin/linux/makefrindex \
	texmf-dist/doc/generic/pst-spirograph/animation/runall.sh \
	texmf-dist/doc/latex/bardiag/example/compile.all \
	texmf-dist/doc/latex/biblatex-abnt/test.sh \
	texmf-dist/doc/latex/biblatex-abnt/texlive.sh \
	texmf-dist/doc/latex/bibunits/bibtexall \
	texmf-dist/doc/latex/confproc/buildprocelpb.sh \
	texmf-dist/doc/latex/confproc/example/buildprocelpb.sh \
	texmf-dist/doc/latex/confproc/example/exportIndividualPDFs.sh \
	texmf-dist/doc/latex/confproc/example/papersinfo.sh \
	texmf-dist/doc/latex/confproc/example/paperssplitpreamble.sh \
	texmf-dist/doc/latex/confproc/example/removeLaTeXcmds.sh \
	texmf-dist/doc/latex/confproc/exportIndividualPDFs.sh \
	texmf-dist/doc/latex/confproc/papersinfo.sh \
	texmf-dist/doc/latex/confproc/paperssplitpreamble.sh \
	texmf-dist/doc/latex/confproc/removeLaTeXcmds.sh \
	texmf-dist/doc/latex/ctable/doit \
	texmf-dist/doc/latex/ctable/inst \
	texmf-dist/doc/latex/curves/latex2pdf \
	texmf-dist/doc/latex/flabels/makedoc-patched \
	texmf-dist/doc/latex/ftc-notebook/newmeeting.sh \
	texmf-dist/doc/latex/hepnames/mkmacrotables \
	texmf-dist/doc/latex/hepthesis/example/getNewBibtex \
	texmf-dist/doc/latex/hvfloat/runAll.sh \
	texmf-dist/doc/latex/hvfloat/runEXA.sh \
	texmf-dist/doc/latex/latex-brochure/build \
	texmf-dist/doc/latex/latex-via-exemplos/makedoc.sh \
	texmf-dist/doc/latex/mathspic/mathspic.sh \
	texmf-dist/doc/latex/milog/milog \
	texmf-dist/doc/latex/multibib/bibtexall \
	texmf-dist/doc/latex/notes/makedoc \
	texmf-dist/doc/latex/pdfreview/pdfreview.sh \
	texmf-dist/doc/latex/pdfreview/pdfshrink.sh \
	texmf-dist/doc/latex/pdftricks/pst2pdf \
	texmf-dist/doc/latex/presentations-en/runAll \
	texmf-dist/doc/latex/seminar/run.sh \
	texmf-dist/doc/latex/seuthesis/a3cover/a3cover.sh \
	texmf-dist/doc/latex/shdoc/shreformat.sh \
	texmf-dist/doc/latex/tengwarscript/install-tengwar-scripts.sh \
	texmf-dist/doc/latex/uspace/uspace-ctanify.sh \
	texmf-dist/doc/lualatex/wallcalendar/doc/examples/diff-cal.sh \
	texmf-dist/doc/metapost/featpost/bash/COMPILE.sh \
	texmf-dist/doc/metapost/featpost/bash/laproof.sh \
	texmf-dist/doc/metapost/featpost/bash/makehtmlindex.sh \
	texmf-dist/doc/plain/plipsum/compile.sh \
	texmf-dist/doc/support/installfont/installfont \
	texmf-dist/doc/support/latexdiff/contrib/latexdiff-wrap \
	texmf-dist/doc/support/latexmk/extra-scripts/pst2pdf_for_latexmk \
	texmf-dist/doc/support/latexmk/extra-scripts/startacroread \
	texmf-dist/dvips/dvipsconfig/addpsctrl \
	texmf-dist/scripts/arara/arara.sh \
	texmf-dist/scripts/bibexport/bibexport.sh.origy \
	texmf-dist/scripts/dtxgen/dtxgen \
	texmf-dist/scripts/installfont/installfont-tl.origy \
	texmf-dist/scripts/latexfileversion/latexfileversion.origy \
	texmf-dist/scripts/logicpuzzle/createlpsudoku \
	texmf-dist/scripts/logicpuzzle/lpsmag \
	texmf-dist/scripts/ltxfileinfo/ltxfileinfo \
	texmf-dist/scripts/lua2dox/lua2dox_filter \
	texmf-dist/scripts/pdftex-quiet/pdftex-quiet \
	texmf-dist/scripts/pdfxup/pdfxup \
	texmf-dist/scripts/shipunov/biokey2html.sh \
	texmf-dist/source/fonts/ae/clean \
	texmf-dist/source/fonts/ae/go \
	texmf-dist/source/fonts/ae/install \
	texmf-dist/source/fonts/ae/makepl \
	texmf-dist/source/fonts/arev/afmtoglyphlist \
	texmf-dist/source/fonts/arev/enctofontpos \
	texmf-dist/source/fonts/arev/makefontfiles \
	texmf-dist/source/fonts/arev/sfdtokernaccent \
	texmf-dist/source/latex/avremu/test-suite/test-suite \
	texmf-dist/source/latex/fifinddo-info/makevars/bashvars.sh \
	texmf-dist/source/latex/fifinddo-info/makevars/texvars.sh \
	texmf-dist/source/latex/stex/bin/installFonts.sh

FONTFORGE_ADJ_FILES += \
	texmf-dist/doc/fonts/berenisadf/ff-ybd.pe \
	texmf-dist/doc/fonts/drm/fontconvert.sh \
	texmf-dist/doc/fonts/gnu-freefont/tools/report/kernclasses.py \
	texmf-dist/doc/fonts/gnu-freefont/tools/utility/metafont/bulk_eps_import.py \
	texmf-dist/source/fonts/arev/fonttokernsfd.ff \
	texmf-dist/source/fonts/arev/fonttopfb.ff \
	texmf-dist/source/fonts/cantarell/sfd2type1.pe \
	texmf-dist/source/fonts/comfortaa/ttf2type1.pe \
	texmf-dist/source/fonts/droid/ttf2type1.pe \
	texmf-dist/source/fonts/fpl/TeXPalladioL-BoldItalicOsF.pe \
	texmf-dist/source/fonts/fpl/TeXPalladioL-BoldOsF.pe \
	texmf-dist/source/fonts/fpl/TeXPalladioL-ItalicOsF.pe \
	texmf-dist/source/fonts/fpl/TeXPalladioL-SC.pe \
	texmf-dist/source/fonts/gentium-tug/type1/ff-gentium.pe \
	texmf-dist/source/fonts/opensans/ttf2type1.pe

LUA_ADJ_FILES += \
	texmf-dist/doc/latex/einfuehrung/foo.lua \
	texmf-dist/doc/latex/einfuehrung2/foo.lua \
	texmf-dist/doc/latex/greek-fontenc/lgr2licr.lua \
	texmf-dist/doc/support/lua-alt-getopt/alt_getopt \
	texmf-dist/tex/lualatex/bezierplot/bezierplot.lua \
	texmf-dist/tex/luatex/luaxml/luaxml-testxml.lua

MODPERL_ADJ_FILES += \
	texmf-dist/doc/metapost/metapost-examples/mp2html.pl \
	texmf-dist/scripts/ketcindy/ketcindy.pl \
	texmf-dist/scripts/ltximg/ltximg.pl \
	texmf-dist/source/support/bibtexperllibs/BibTeX-Parser/t/release-pod-coverage.t \
	texmf-dist/source/support/bibtexperllibs/BibTeX-Parser/t/release-pod-syntax.t \
	texmf-dist/source/support/bibtexperllibs/LaTeX-ToUnicode/t/release-pod-coverage.t \
	texmf-dist/source/support/bibtexperllibs/LaTeX-ToUnicode/t/release-pod-syntax.t \
	texmf-dist/source/support/bibtexperllibs/LaTeX-ToUnicode/t/release-synopsis.t

PYTHON2_ADJ_FILES += \
	texmf-dist/asymptote/GUI/UndoRedoStack.py \
	texmf-dist/asymptote/GUI/xasy.py \
	texmf-dist/asymptote/GUI/xasy2asy.py \
	texmf-dist/asymptote/GUI/xasyFile.py \
	texmf-dist/asymptote/GUI/xasyOptions.py \
	texmf-dist/asymptote/GUI/xasyVersion.py \
	texmf-dist/doc/fonts/gnu-freefont/tools/test/ranges/Arabic/arabic_test.py \
	texmf-dist/doc/fonts/gnu-freefont/tools/test/ranges/Arabic/generate_arabic_shaping.py \
	texmf-dist/doc/fonts/gnu-freefont/tools/test/ranges/Arabic/unicode_joining.py \
	texmf-dist/doc/fonts/gnu-freefont/tools/utility/hex_range.py \
	texmf-dist/doc/fonts/punknova/tools/build.py \
	texmf-dist/doc/fonts/xcharter/altone.py \
	texmf-dist/doc/generic/enctex/unimap.py \
	texmf-dist/doc/latex/aramaic-serto/serto.py \
	texmf-dist/doc/latex/biblatex-bookinother/documentation/generate-crossref-graphs.py \
	texmf-dist/doc/latex/biblatex-gb7714-2015/biblatex_check.py \
	texmf-dist/doc/latex/biblatex-morenames/documentation/generate-crossref-graphs.py \
	texmf-dist/doc/latex/ejpecp/mgetmref.py \
	texmf-dist/doc/latex/newcommand/newcommand.py \
	texmf-dist/doc/latex/pythontex/syncpdb.py \
	texmf-dist/doc/latex/scanpages/replicate.py \
	texmf-dist/doc/plain/plipsum/stripc \
	texmf-dist/doc/support/hook-pre-commit-pkg/pre-commit-latex \
	texmf-dist/doc/support/latexdiff/contrib/latexchanges.py \
	texmf-dist/doc/xelatex/xepersian/dkun-0.3.py \
	texmf-dist/doc/xelatex/xepersian/dkun-0.4.py \
	texmf-dist/doc/xelatex/xepersian/undk-0.6.py \
	texmf-dist/doc/xelatex/xepersian/unldk-0.2.py \
	texmf-dist/scripts/changes/pyMergeChanges.py \
	texmf-dist/scripts/de-macro/de-macro \
	texmf-dist/scripts/dviasm/dviasm.py \
	texmf-dist/scripts/ebong/ebong.py \
	texmf-dist/scripts/latex-make/figdepth.py \
	texmf-dist/scripts/latex-make/gensubfig.py \
	texmf-dist/scripts/latex-make/latexfilter.py \
	texmf-dist/scripts/latex-make/svg2dev.py \
	texmf-dist/scripts/latex-make/svgdepth.py \
	texmf-dist/scripts/latex-papersize/latex-papersize.py \
	texmf-dist/scripts/lilyglyphs/lily-glyph-commands.py \
	texmf-dist/scripts/lilyglyphs/lily-image-commands.py \
	texmf-dist/scripts/lilyglyphs/lily-rebuild-pdfs.py \
	texmf-dist/scripts/lilyglyphs/lilyglyphs_common.py \
	texmf-dist/scripts/pdfbook2/pdfbook2 \
	texmf-dist/scripts/pygmentex/pygmentex.py \
	texmf-dist/scripts/pythontex/depythontex.py \
	texmf-dist/scripts/pythontex/depythontex2.py \
	texmf-dist/scripts/pythontex/pythontex.py \
	texmf-dist/scripts/pythontex/pythontex2.py \
	texmf-dist/scripts/pythontex/pythontex_2to3.py \
	texmf-dist/scripts/pythontex/pythontex_install.py \
	texmf-dist/scripts/texliveonfly/texliveonfly.py \
	texmf-dist/source/fonts/fonts-tlwg/scripts/gen-test-ttf.py \
	texmf-dist/source/fonts/fonts-tlwg/scripts/gen-ttf.py \
	texmf-dist/source/fonts/gentium-tug/type1/afmcreator.py \
	texmf-dist/source/fonts/gentium-tug/type1/greekcorrection.py \
	texmf-dist/source/fonts/gentium-tug/type1/kerncorrection.py

PYTHON3_ADJ_FILES += \
	texmf-dist/asymptote/GUI/CustMatTransform.py \
	texmf-dist/asymptote/GUI/DebugFlags.py \
	texmf-dist/asymptote/GUI/GuidesManager.py \
	texmf-dist/asymptote/GUI/InplaceAddObj.py \
	texmf-dist/asymptote/GUI/PrimitiveShape.py \
	texmf-dist/asymptote/GUI/SetCustomAnchor.py \
	texmf-dist/asymptote/GUI/Widg_addLabel.py \
	texmf-dist/asymptote/GUI/Widg_addPolyOpt.py \
	texmf-dist/asymptote/GUI/Widg_editBezier.py \
	texmf-dist/asymptote/GUI/Window1.py \
	texmf-dist/asymptote/GUI/__init__.py \
	texmf-dist/asymptote/GUI/labelEditor.py \
	texmf-dist/asymptote/GUI/setup.py \
	texmf-dist/asymptote/GUI/xasyArgs.py \
	texmf-dist/asymptote/GUI/xasyBezierInterface.py \
	texmf-dist/asymptote/GUI/xasyStrings.py \
	texmf-dist/asymptote/GUI/xasySvg.py \
	texmf-dist/asymptote/GUI/xasyTransform.py \
	texmf-dist/asymptote/GUI/xasyUtils.py \
	texmf-dist/asymptote/GUI/xasyValidator.py \
	texmf-dist/asymptote/asymptote.py \
	texmf-dist/doc/metapost/metapost-colorbrewer/make_mp_colorbrewer.py \
	texmf-dist/doc/support/gitfile-info/gfi-run.py \
	texmf-dist/doc/support/gitfile-info/post-commit.py \
	texmf-dist/doc/support/gitfile-info/post-merge.py \
	texmf-dist/scripts/pythontex/depythontex3.py \
	texmf-dist/scripts/pythontex/pythontex3.py \
	texmf-dist/scripts/webquiz/webquiz \
	texmf-dist/scripts/webquiz/webquiz.py \
	texmf-dist/scripts/webquiz/webquiz_makequiz.py \
	texmf-dist/scripts/webquiz/webquiz_util.py

RUBY_ADJ_FILES += \
	texmf-dist/doc/generic/huhyphen/searchforerrors.rb \
	texmf-dist/doc/generic/huhyphen/testhyphenation.rb \
	texmf-dist/doc/latex/cd/parsecd.rb \
	texmf-dist/scripts/context/ruby/ctxtools.rb \
	texmf-dist/scripts/context/ruby/imgtopdf.rb \
	texmf-dist/scripts/context/ruby/pdftools.rb \
	texmf-dist/scripts/context/ruby/pstopdf.rb \
	texmf-dist/scripts/context/ruby/rlxtools.rb \
	texmf-dist/scripts/context/ruby/texexec.rb \
	texmf-dist/scripts/context/ruby/texmfstart.rb \
	texmf-dist/scripts/context/ruby/textools.rb \
	texmf-dist/scripts/context/ruby/tmftools.rb \
	texmf-dist/scripts/context/ruby/xmltools.rb \
	texmf-dist/scripts/convbkmk/convbkmk.rb \
	texmf-dist/scripts/match_parens/match_parens \
	texmf-dist/source/fonts/gentium-tug/generate-support-files.rb \
	texmf-dist/source/fonts/japanese-otf/script/otf-hangul.rb \
	texmf-dist/source/generic/hyph-utf8/generate-converters.rb \
	texmf-dist/source/generic/hyph-utf8/generate-pattern-loaders.rb \
	texmf-dist/source/generic/hyph-utf8/generate-plain-patterns.rb \
	texmf-dist/source/generic/hyph-utf8/generate-ptex-patterns.rb \
	texmf-dist/source/generic/hyph-utf8/generate-tl-files.rb \
	texmf-dist/source/generic/hyph-utf8/languages/eu/generate_patterns_eu.rb \
	texmf-dist/source/generic/hyph-utf8/languages/hy/generate_patterns_hy.rb \
	texmf-dist/source/generic/hyph-utf8/languages/tk/generate_patterns_tk.rb \
	texmf-dist/source/generic/hyph-utf8/languages/tr/generate_patterns_tr.rb \
	texmf-dist/source/latex/proposal/bin/generate-issues \
	texmf-dist/source/luatex/luatexja/tool/blocks2defcharrange.rb \
	texmf-dist/source/luatex/luatexja/tool/chars2defcharrange.rb \
	texmf-dist/source/luatex/luatexja/tool/jfm-readable.rb

TEXLUA_ADJ_FILES += \
	texmf-dist/doc/fonts/zhmetrics-uptex/makemetrics.lua \
	texmf-dist/doc/generic/m-tx/buildmtxdoc.lua \
	texmf-dist/doc/support/cluttex/src/cluttex.lua \
	texmf-dist/scripts/cachepic/cachepic.tlu \
	texmf-dist/scripts/checkcites/checkcites.lua \
	texmf-dist/scripts/cluttex/cluttex.lua \
	texmf-dist/scripts/context/lua/mtxrun.lua \
	texmf-dist/scripts/context/lua/third/rst/mtx-t-rst.lua \
	texmf-dist/scripts/context/stubs/mswin/mtxrun.lua \
	texmf-dist/scripts/context/stubs/unix/mtxrun \
	texmf-dist/scripts/context/stubs/unix/mtxrun.beforesubst \
	texmf-dist/scripts/context/stubs/unix/mtxrun.origy \
	texmf-dist/scripts/context/stubs/win64/mtxrun.lua \
	texmf-dist/scripts/ctanbib/ctanbib \
	texmf-dist/scripts/diadia/diadia.lua \
	texmf-dist/scripts/epspdf/epspdf.tlu \
	texmf-dist/scripts/getmap/getmapdl.lua \
	texmf-dist/scripts/glossaries/makeglossaries-lite.lua \
	texmf-dist/scripts/l3build/l3build.lua \
	texmf-dist/scripts/luaotfload/luaotfload-tool.lua \
	texmf-dist/scripts/lwarp/lwarpmk.lua \
	texmf-dist/scripts/m-tx/m-tx.lua \
	texmf-dist/scripts/make4ht/make4ht \
	texmf-dist/scripts/musixtex/musixflx.lua \
	texmf-dist/scripts/musixtex/musixtex.lua \
	texmf-dist/scripts/pfarrei/a5toa4.tlu \
	texmf-dist/scripts/pfarrei/pfarrei.tlu \
	texmf-dist/scripts/pmx/pmx2pdf.lua \
	texmf-dist/scripts/pmxchords/pmxchords.lua \
	texmf-dist/scripts/ptex2pdf/ptex2pdf.lua \
	texmf-dist/scripts/splitindex/splitindex.tlu \
	texmf-dist/scripts/splitindex/splitindex_main.tlu \
	texmf-dist/scripts/tex4ebook/tex4ebook \
	texmf-dist/scripts/texdoc/texdoc.tlu \
	texmf-dist/scripts/texlive/lua/texlive/getopt.tlu \
	texmf-dist/scripts/texlive/lua/texlive/tlpdb.tlu \
	texmf-dist/scripts/texlive/rungs.tlu \
	texmf-dist/scripts/texlive/test-tlpdb.tlu \
	texmf-dist/scripts/texlive/texconf.tlu \
	texmf-dist/scripts/tlgs/gswin32/eps2eps.tlu \
	texmf-dist/scripts/tlgs/gswin32/pdf2dsc.tlu \
	texmf-dist/scripts/tlgs/gswin32/pdfopt.tlu \
	texmf-dist/scripts/tlgs/gswin32/ps2ascii.tlu \
	texmf-dist/scripts/tlgs/gswin32/ps2pdf.tlu \
	texmf-dist/scripts/tlgs/gswin32/ps2pdf12.tlu \
	texmf-dist/scripts/tlgs/gswin32/ps2pdf13.tlu \
	texmf-dist/scripts/tlgs/gswin32/ps2pdf14.tlu \
	texmf-dist/scripts/tlgs/gswin32/ps2ps.tlu \
	texmf-dist/scripts/xindex/xindex.lua \
	texmf-dist/source/generic/hyph-utf8/languages/mul-ethi/generate_patterns_mul-ethi.lua \
	texmf-dist/source/luatex/luatexja/tool/jfm-convert.lua \
	texmf-dist/source/ptex-fontmaps/jis04cmap_exp/mk_jis_to_aj16_cid.lua \
	texmf-dist/tex/context/third/cyrillicnumbers/cyrillicnumbers.lua \
	texmf-dist/tex/context/third/rst/rst_context.lua \
	texmf-dist/tex/context/third/rst/rst_directives.lua \
	texmf-dist/tex/context/third/rst/rst_helpers.lua \
	texmf-dist/tex/context/third/rst/rst_parser.lua \
	texmf-dist/tex/context/third/rst/rst_setups.lua \
	texmf-dist/tex/context/third/transliterator/transliterator.lua \
	texmf-dist/tex/generic/enigma/enigma.lua \
	texmf-dist/tex/luatex/lualibs/lualibs-compat.lua

WISH_ADJ_FILES += \
	texmf-dist/scripts/epspdf/epspdftk.tcl \
	texmf-dist/scripts/tlshell/tlshell.tcl
