# $OpenBSD: Makefile,v 1.4 2005/11/17 17:09:50 naddy Exp $

COMMENT=	"Phase of the Moon for GkrellM2"

DISTNAME=	gkrellmoon-0.6
PKGNAME=	${DISTNAME}p2
CATEGORIES=	astro sysutils/gkrellm

HOMEPAGE=	http://gkrellmoon.sourceforge.net/

MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=gkrellmoon/}

ALL_TARGET=	gkrellmoon.so
PLUGIN=		${WRKSRC}/gkrellmoon.so

.include <bsd.port.mk>
