# $OpenBSD: Makefile,v 1.45 2007/11/14 12:04:04 kurt Exp $
# $FreeBSD: Makefile,v 1.27 1997/11/22 14:56:56 peter Exp $

     SUBDIR += birda
     SUBDIR += bottlerocket
     SUBDIR += colrdx
     SUBDIR += conserver
     SUBDIR += efax
     SUBDIR += flipit
     SUBDIR += gmfsk
     SUBDIR += gnokii
     SUBDIR += gpsk31
     SUBDIR += hamlib
     SUBDIR += hylafax
     SUBDIR += hylafax,a4
     SUBDIR += jpilot
     SUBDIR += jpilot-syncmal
     SUBDIR += kermit
     SUBDIR += libmal
     SUBDIR += lrzsz
     SUBDIR += mgetty+sendfax
     SUBDIR += minicom
     SUBDIR += obexftp
     SUBDIR += openobex
     SUBDIR += p5-Device-Gsm
     SUBDIR += p5-Device-Modem
     SUBDIR += p5-Device-SerialPort
     SUBDIR += p5-SendPage
     SUBDIR += pilot-link
     SUBDIR += qpage
     SUBDIR += scmxx
     SUBDIR += seyon
     SUBDIR += smstools
     SUBDIR += sredird
     SUBDIR += tkhylafax
     SUBDIR += tlf
     SUBDIR += wy60
     SUBDIR += x3270
     SUBDIR += xastir
     SUBDIR += xcept
     SUBDIR += xdx
     SUBDIR += xlog
     SUBDIR += zmtx-zmrx

.include <bsd.port.subdir.mk>
