COMMENT=	Python port of the parser used internally by GNU bash

MODPY_DISTV=	0.18
DISTNAME=	bashlex-${MODPY_DISTV}
PKGNAME=	py-${DISTNAME}
CATEGORIES=	textproc sysutils
REVISION=	1

HOMEPAGE=	https://github.com/idank/bashlex

# GPLv3+
PERMIT_PACKAGE=	Yes

MODPY_PI=	Yes
MODPY_PYBUILD=	setuptools

MODULES=	lang/python

.include <bsd.port.mk>
