# Load the sndio spa plugin and create sink and source nodes on the
# default sndio device.
# sio_open(3) honours $AUDIODEVICE; set api.sndio.path to select
# another device.
context.spa-libs = {
    api.sndio.* = sndio/libspa-sndio
}

context.objects = [
    { factory = adapter
        args = {
            factory.name     = api.sndio.pcm.sink
            node.name        = "sndio-sink"
            node.description = "sndio sink"
            media.class      = "Audio/Sink"
            priority.session = 1000
            priority.driver  = 1000
            #api.sndio.path  = "default"
            audio.position   = [ FL FR ]
        }
        flags = [ nofail ]
    }
    { factory = adapter
        args = {
            factory.name     = api.sndio.pcm.source
            node.name        = "sndio-source"
            node.description = "sndio source"
            media.class      = "Audio/Source"
            priority.session = 900
            priority.driver  = 900
            #api.sndio.path  = "default"
            audio.position   = [ FL FR ]
        }
        flags = [ nofail ]
    }
]
