# $OpenBSD: Makefile,v 1.9 2020/07/03 21:45:30 sthen Exp $

COMMENT=	parse and create IIF files for QuickBooks

MODULES=	cpan
PKG_ARCH=	*
DISTNAME=	Finance-IIF-0.20.01
REVISION=	2
CATEGORIES=	misc

# Perl
PERMIT_PACKAGE=	Yes

.include <bsd.port.mk>
