# $OpenBSD: Makefile,v 1.8 2019/07/12 20:47:52 sthen Exp $

COMMENT=	parse and create IIF files for QuickBooks

MODULES=	cpan
PKG_ARCH=	*
DISTNAME=	Finance-IIF-0.20.01
REVISION=	1
CATEGORIES=	misc

# Perl
PERMIT_PACKAGE=	Yes

.include <bsd.port.mk>
