# $OpenBSD: Makefile,v 1.1.1.1 2009/06/17 09:36:52 robert Exp $

COMMENT=	HTML tag cloud generator

MODULES=	cpan
DISTNAME=	HTML-TagCloud-0.34
CATEGORIES=	www

# Perl
PERMIT_PACKAGE_CDROM=  Yes
PERMIT_PACKAGE_FTP=    Yes
PERMIT_DISTFILES_CDROM=Yes
PERMIT_DISTFILES_FTP=  Yes

.include <bsd.port.mk>
