#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pep517', 'pep517.in_process']

package_data = \
{'': ['*']}

extras_require = \
{":python_version<'3.6'": ['toml'],
 ":python_version<'3.8'": ['importlib_metadata', 'zipp'],
 ":python_version>='3.6'": ['tomli >=1.1.0']}

setup(name='pep517',
      version='${MODPY_EGG_VERSION}',
      description='Wrappers to build Python packages using PEP 517 hooks',
      author='Thomas Kluyver',
      author_email='thomas@kluyver.me.uk',
      url='https://github.com/pypa/pep517',
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
     )
