# $OpenBSD: Makefile,v 1.5 1999/09/23 21:58:00 brad Exp $

DISTNAME=	sattrack-3.1.6
CATEGORIES=	astro
MASTER_SITES=   ${MASTER_SITE_LOCAL}

NO_CDROM=	"COPY: may not be bundled"

MAINTAINER=	angelos@openbsd.org

WRKSRC=		${WRKDIR}/SatTrack-3.1.6/src

.include <bsd.port.mk>
