# $OpenBSD: Makefile,v 1.5 2017/04/29 10:09:10 benoit Exp $

COMMENT =	test fallback behaviour in absence of modules

DISTNAME =	Test-Without-Module-0.20
CATEGORIES =	devel

# Perl
PERMIT_PACKAGE_CDROM = Yes

MODULES =	cpan
PKG_ARCH =	*

.include <bsd.port.mk>
