# $OpenBSD: Makefile,v 1.22 2021/03/15 20:53:23 sthen Exp $

COMMENT =	simple parallel processing fork manager

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	Parallel-ForkManager-2.02
CATEGORIES =	devel
REVISION =	0

# perl
PERMIT_PACKAGE =	Yes

MODCPAN_EXAMPLES =	Yes

TEST_DEPENDS =		devel/p5-Test-Warn

.include <bsd.port.mk>
