# $OpenBSD: Makefile,v 1.4 2016/03/20 19:56:17 naddy Exp $

COMMENT=	compare perl data structures

DISTNAME=	Data-Compare-1.22
REVISION=	0
CATEGORIES=	devel

MAINTAINER=	Andrew Fresh <afresh1@openbsd.org>

# Same as Perl
PERMIT_PACKAGE_CDROM=	Yes

MODULES=		cpan
PKG_ARCH=		*
RUN_DEPENDS=		devel/p5-File-Find-Rule

.include <bsd.port.mk>
