# $OpenBSD: Makefile,v 1.10 2015/12/20 11:27:22 kili Exp $

COMMENT=		provides Word128, Word192 and various others large words

DISTNAME=		largeword-1.0.5
CATEGORIES=		devel
REVISION=		3

# BSD3
PERMIT_PACKAGE_CDROM =	Yes

MODULES=		lang/ghc

MODGHC_BUILD =          cabal hackage haddock register

MODGHC_PACKAGE_KEY =	G3v3uYLovUWKgLK8yxlUqn

.include <bsd.port.mk>
