# $OpenBSD: Makefile,v 1.1.1.1 2012/04/10 12:50:24 espie Exp $

COMMENT =	date cck and api for drupal
MAINTAINER =	Marc Espie <espie@openbsd.org>

DISTNAME = 	date-7.x-2.3
PKGNAME =	drupal7-date-2.3

RUN_DEPENDS =	www/drupal6/cck

.include <bsd.port.mk>
