# $OpenBSD: Makefile,v 1.9 2014/03/23 14:27:39 jasper Exp $

COMMENT= 	alternative object layout in perl

MODULES=	cpan

DISTNAME=	Class-InsideOut-1.09
REVISION=	1

CATEGORIES=	devel
USE_GROFF=	Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes

CONFIGURE_STYLE=modbuild

RUN_DEPENDS=	devel/p5-Class-ISA

.include <bsd.port.mk>
