# $OpenBSD: Makefile,v 1.21 2006/02/12 14:58:15 david Exp $
# $FreeBSD: Makefile,v 1.4 1997/06/03 09:14:50 asami Exp $

     SUBDIR += dgpsip
     SUBDIR += jday
     SUBDIR += luna
     SUBDIR += phoon
     SUBDIR += py-metar
     SUBDIR += sattrack
     SUBDIR += sunclock
     SUBDIR += wmglobe
     SUBDIR += wmmoonclock
     SUBDIR += wmspaceweather
     SUBDIR += wmsun
     SUBDIR += xearth
     SUBDIR += xephem
     SUBDIR += xphoon
     SUBDIR += xworld

.include <bsd.port.subdir.mk>
