# $OpenBSD: Makefile,v 1.13 2013/08/12 04:11:21 robert Exp $

COMMENT=	contact management module, for Horde

# Horde license (BSD-like with some restrictions, see LICENSE)
DISTNAME=	turba-h3-2.3.6
REVISION=	2

RUN_DEPENDS=	www/horde/imp

.include <bsd.port.mk>
