# $OpenBSD: Makefile,v 1.6 2013/10/11 23:48:42 naddy Exp $

COMMENT =		common perl data validation methods

DISTNAME =		Data-Validate-0.08
REVISION =		0

CATEGORIES =		devel

MAINTAINER =		Alexander Bluhm <bluhm@openbsd.org>

# perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

.include <bsd.port.mk>
