# $OpenBSD: Makefile,v 1.14 2015/01/21 06:13:47 bentley Exp $

COMMENT=	module to create Markov chains and output based on them

MODULES=	cpan
DISTNAME=	Algorithm-MarkovChain-0.06
REVISION=	2
CATEGORIES=	devel
USE_GROFF =	Yes

PERMIT_PACKAGE_CDROM=   Yes

.include <bsd.port.mk>
