# $OpenBSD: Makefile,v 1.8 2010/07/13 20:14:21 sthen Exp $

COMMENT=	module to implement an accurate neural network mesh

MODULES=	cpan
DISTNAME=	AI-NeuralNet-Mesh-0.44
REVISION=	0
CATEGORIES=	math

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

EXTRACT_SUFX=	.zip

WRKDIST=	${WRKDIR}

.include <bsd.port.mk>
