COMMENT=	module to implement an accurate neural network mesh

MODULES=	cpan
PKG_ARCH=	*
DISTNAME=	AI-NeuralNet-Mesh-0.44
REVISION=	3
CATEGORIES=	math

# Perl
PERMIT_PACKAGE=	Yes

EXTRACT_SUFX=	.zip

WRKDIST=	${WRKDIR}

.include <bsd.port.mk>
