# $OpenBSD: Makefile,v 1.4 2021/11/02 00:02:04 sthen Exp $

MODPY_EGG_VERSION =	5.2.1
TRYTON_MODULE =		dashboard
REVISION =		1

RUN_DEPENDS +=		databases/py-sql${MODPY_FLAVOR} \
			textproc/py-lxml${MODPY_FLAVOR}

.include <bsd.port.mk>
